import type { ClueRecord } from '@/types'

export const CLUE_DATASET: ClueRecord[] = [
  { answer: 'ERA', clue: 'Stretch of history' },
  { answer: 'ERA', clue: 'Big name in pitching stats' },
  { answer: 'ORE', clue: 'Mine find' },
  { answer: 'ORE', clue: 'Smeltery input' },
  { answer: 'ATE', clue: 'Had dinner' },
  { answer: 'ATE', clue: 'Gobbled up' },
  { answer: 'ETA', clue: 'Airport guess, for short' },
  { answer: 'ETA', clue: 'Pilot\'s announcement, briefly' },
  { answer: 'ARC', clue: 'Rainbow shape' },
  { answer: 'ARC', clue: 'Story line progression' },
  { answer: 'ACE', clue: 'Card that beats a king' },
  { answer: 'ACE', clue: 'Top-notch' },
  { answer: 'APE', clue: 'Gorilla or gibbon' },
  { answer: 'APE', clue: 'Copy, slangily' },
  { answer: 'ART', clue: 'Gallery hangings' },
  { answer: 'ART', clue: 'Works in a museum' },
  { answer: 'ARM', clue: 'Sleeve filler' },
  { answer: 'ARM', clue: 'Prepare for battle' },
  { answer: 'ANT', clue: 'Picnic pest' },
  { answer: 'ANT', clue: 'Colony member' },
  { answer: 'ADO', clue: 'Commotion' },
  { answer: 'ADO', clue: 'Much ___ About Nothing' },
  { answer: 'ALE', clue: 'Pub pint' },
  { answer: 'ALE', clue: 'Brewery offering' },
  { answer: 'ALL', clue: 'Every last one' },
  { answer: 'ALL', clue: 'The whole enchilada' },
  { answer: 'APT', clue: 'Quick to learn' },
  { answer: 'APT', clue: 'Fitting' },
  { answer: 'ASH', clue: 'Fireplace residue' },
  { answer: 'ASH', clue: 'Volcanic output' },
  { answer: 'AWE', clue: 'Leave speechless' },
  { answer: 'AWE', clue: 'Wonderment' },
  { answer: 'AXE', clue: 'Lumberjack\'s tool' },
  { answer: 'AXE', clue: 'Give the boot' },
  { answer: 'BAD', clue: 'Not good' },
  { answer: 'BAD', clue: 'Rotten' },
  { answer: 'BAG', clue: 'Grocery carrier' },
  { answer: 'BAG', clue: 'Capture' },
  { answer: 'BAT', clue: 'Cave dweller' },
  { answer: 'BAT', clue: 'Cricket equipment' },
  { answer: 'BED', clue: 'Place to sleep' },
  { answer: 'BED', clue: 'Garden plot' },
  { answer: 'BEE', clue: 'Honey maker' },
  { answer: 'BEE', clue: 'Spelling competition' },
  { answer: 'BET', clue: 'Wager' },
  { answer: 'BET', clue: 'Track transaction' },
  { answer: 'BID', clue: 'Auction action' },
  { answer: 'BID', clue: 'Attempt' },
  { answer: 'BIG', clue: 'Large' },
  { answer: 'BIG', clue: 'Important, informally' },
  { answer: 'BIT', clue: 'Tiny piece' },
  { answer: 'BIT', clue: 'Drill attachment' },
  { answer: 'BOX', clue: 'Cardboard container' },
  { answer: 'BOX', clue: 'Fight sport' },
  { answer: 'BOY', clue: 'Young lad' },
  { answer: 'BOY', clue: 'Exclamation of surprise' },
  { answer: 'BUS', clue: 'School transport' },
  { answer: 'BUS', clue: 'Clear tables, in diner slang' },
  { answer: 'CAB', clue: 'Taxi' },
  { answer: 'CAB', clue: 'Wine variety' },
  { answer: 'CAN', clue: 'Is able to' },
  { answer: 'CAN', clue: 'Soup container' },
  { answer: 'CAP', clue: 'Baseball headwear' },
  { answer: 'CAP', clue: 'Upper limit' },
  { answer: 'CAR', clue: 'Auto' },
  { answer: 'CAR', clue: 'Elevator compartment' },
  { answer: 'CAT', clue: 'Feline' },
  { answer: 'CAT', clue: 'Jazz aficionado' },
  { answer: 'COW', clue: 'Dairy farm animal' },
  { answer: 'COW', clue: 'Intimidate' },
  { answer: 'CRY', clue: 'Weep' },
  { answer: 'CRY', clue: 'Shout' },
  { answer: 'CUP', clue: 'Coffee holder' },
  { answer: 'CUP', clue: 'Trophy' },
  { answer: 'CUT', clue: 'Slice' },
  { answer: 'CUT', clue: 'Film editor\'s removal' },
  { answer: 'DAM', clue: 'Beaver\'s project' },
  { answer: 'DAM', clue: 'River blocker' },
  { answer: 'DAY', clue: '24-hour period' },
  { answer: 'DAY', clue: 'Times partner' },
  { answer: 'DEN', clue: 'Lion\'s lair' },
  { answer: 'DEN', clue: 'Family room' },
  { answer: 'DEW', clue: 'Morning moisture' },
  { answer: 'DEW', clue: 'Mountain ___ (soda)' },
  { answer: 'DOG', clue: 'Canine' },
  { answer: 'DOG', clue: 'Follow persistently' },
  { answer: 'DOT', clue: 'Polka ___' },
  { answer: 'DOT', clue: 'On the ___ (precisely)' },
  { answer: 'DRY', clue: 'Not wet' },
  { answer: 'DRY', clue: 'Prohibitionist' },
  { answer: 'DUE', clue: 'Owed' },
  { answer: 'DUE', clue: 'Expected' },
  { answer: 'EGG', clue: 'Omelet need' },
  { answer: 'EGG', clue: 'Incite, with "on"' },
  { answer: 'ELF', clue: 'Workshop helper' },
  { answer: 'ELF', clue: ' Tolkien creature' },
  { answer: 'ELK', clue: 'Large deer' },
  { answer: 'ELK', clue: 'Lodge member' },
  { answer: 'END', clue: 'Conclusion' },
  { answer: 'END', clue: 'Gridiron position' },
  { answer: 'EYE', clue: 'Organ of sight' },
  { answer: 'EYE', clue: 'Hurricane center' },
  { answer: 'FAN', clue: 'Ceiling spinner' },
  { answer: 'FAN', clue: 'Devoted follower' },
  { answer: 'FAR', clue: 'Distant' },
  { answer: 'FAR', clue: 'Way out there' },
  { answer: 'FAT', clue: 'Dietary concern' },
  { answer: 'FAT', clue: 'Marbling, on a steak' },
  { answer: 'FED', clue: 'Gave dinner to' },
  { answer: 'FED', clue: 'The ___ (central bank, with "the")' },
  { answer: 'FEW', clue: 'Not many' },
  { answer: 'FEW', clue: 'A handful of' },
  { answer: 'FIG', clue: 'Newton fruit' },
  { answer: 'FIG', clue: 'Mediterranean fruit' },
  { answer: 'FIN', clue: 'Shark feature' },
  { answer: 'FIN', clue: 'Fish appendage' },
  { answer: 'FLY', clue: 'Take to the air' },
  { answer: 'FLY', clue: 'Zipper alternative' },
  { answer: 'FOE', clue: 'Enemy' },
  { answer: 'FOE', clue: 'Adversary' },
  { answer: 'FOG', clue: 'Driving hazard' },
  { answer: 'FOG', clue: 'London weather' },
  { answer: 'FUN', clue: 'Amusement' },
  { answer: 'FUN', clue: 'Good time' },
  { answer: 'FUR', clue: 'Mink coat material' },
  { answer: 'FUR', clue: 'Cat coat' },
  { answer: 'GAP', clue: 'Opening' },
  { answer: 'GAP', clue: 'Clothing store name' },
  { answer: 'GAS', clue: 'Fuel' },
  { answer: 'GAS', clue: 'Helium or neon' },
  { answer: 'GEL', clue: 'Hair stiffener' },
  { answer: 'GEL', clue: 'Set, as plans' },
  { answer: 'GEM', clue: 'Precious stone' },
  { answer: 'GEM', clue: 'Ruby or emerald' },
  { answer: 'GET', clue: 'Obtain' },
  { answer: 'GET', clue: 'Fetch' },
  { answer: 'GOD', clue: 'Deity' },
  { answer: 'GOD', clue: 'Olympian figure' },
  { answer: 'GOT', clue: 'Acquired' },
  { answer: 'GOT', clue: ' HBO series, briefly' },
  { answer: 'GUM', clue: 'Chewy candy' },
  { answer: 'GUM', clue: 'Bubble blower\'s need' },
  { answer: 'GUN', clue: 'Firearm' },
  { answer: 'GUN', clue: 'Race engine' },
  { answer: 'GUT', clue: 'Instinct, with "feeling"' },
  { answer: 'GUT', clue: 'Stomach, informally' },
  { answer: 'GYM', clue: 'Workout spot' },
  { answer: 'GYM', clue: 'School class with mats' },
  { answer: 'HAD', clue: 'Possessed' },
  { answer: 'HAD', clue: 'Tricked, with "on"' },
  { answer: 'HAM', clue: 'Deli meat' },
  { answer: 'HAM', clue: 'Overactor' },
  { answer: 'HAT', clue: 'Head covering' },
  { answer: 'HAT', clue: 'Tip of the ___ (respect gesture)' },
  { answer: 'HEN', clue: 'Coop resident' },
  { answer: 'HEN', clue: 'Egg layer' },
  { answer: 'HER', clue: 'That woman\'s' },
  { answer: 'HER', clue: 'She, objectively' },
  { answer: 'HID', clue: 'Concealed' },
  { answer: 'HID', clue: 'Stashed away' },
  { answer: 'HIM', clue: 'That guy, objectively' },
  { answer: 'HIM', clue: 'Pronoun for a lad' },
  { answer: 'HIP', clue: 'Trendy' },
  { answer: 'HIP', clue: 'Pelvis part' },
  { answer: 'HIT', clue: 'Chart topper' },
  { answer: 'HIT', clue: 'Strike, as a ball' },
  { answer: 'HOG', clue: 'Farm animal' },
  { answer: 'HOG', clue: 'Monopolize' },
  { answer: 'HOP', clue: 'Jump on one foot' },
  { answer: 'HOP', clue: 'Brewery ingredient' },
  { answer: 'HOT', clue: 'Spicy' },
  { answer: 'HOT', clue: 'Trending' },
  { answer: 'HOW', clue: 'In what way' },
  { answer: 'HOW', clue: 'Question word' },
  { answer: 'HUB', clue: 'Airport center' },
  { answer: 'HUB', clue: 'Wheel center' },
  { answer: 'HUE', clue: 'Color shade' },
  { answer: 'HUE', clue: 'Tint' },
  { answer: 'HUG', clue: 'Embrace' },
  { answer: 'HUG', clue: 'Warm greeting' },
  { answer: 'HUM', clue: 'Sing without words' },
  { answer: 'HUM', clue: 'Low steady sound' },
  { answer: 'ICE', clue: 'Frozen water' },
  { answer: 'ICE', clue: 'Rink surface' },
  { answer: 'ILL', clue: 'Under the weather' },
  { answer: 'ILL', clue: 'Poorly' },
  { answer: 'INK', clue: 'Printer supply' },
  { answer: 'INK', clue: 'Tattooist\'s medium' },
  { answer: 'INN', clue: 'Roadside lodging' },
  { answer: 'INN', clue: 'Quaint hotel' },
  { answer: 'ION', clue: 'Charged particle' },
  { answer: 'ION', clue: 'Physics bit' },
  { answer: 'IRK', clue: 'Annoy' },
  { answer: 'IRK', clue: 'Vex' },
  { answer: 'ITS', clue: 'Belonging to that thing' },
  { answer: 'ITS', clue: 'The "I" in "T.G.I.F."' },
  { answer: 'JAM', clue: 'Traffic snarl' },
  { answer: 'JAM', clue: 'Toast topper' },
  { answer: 'JAR', clue: 'Pickle container' },
  { answer: 'JAR', clue: 'Startle' },
  { answer: 'JAW', clue: 'Mandible' },
  { answer: 'JAW', clue: 'Chat at length, with "on"' },
  { answer: 'JET', clue: 'Airplane' },
  { answer: 'JET', clue: 'Black gemstone' },
  { answer: 'JOB', clue: 'Employment' },
  { answer: 'JOB', clue: 'Task' },
  { answer: 'JOG', clue: 'Easy run' },
  { answer: 'JOG', clue: 'Nudge a memory' },
  { answer: 'JOY', clue: 'Delight' },
  { answer: 'JOY', clue: 'Happiness' },
  { answer: 'JUG', clue: 'Water pitcher' },
  { answer: 'JUG', clue: 'Large container' },
  { answer: 'JUT', clue: 'Stick out' },
  { answer: 'JUT', clue: 'Protrude' },
  { answer: 'KEY', clue: 'Lock opener' },
  { answer: 'KEY', clue: 'Crucial' },
  { answer: 'KID', clue: 'Child' },
  { answer: 'KID', clue: 'Goat young' },
  { answer: 'KIN', clue: 'Relatives' },
  { answer: 'KIN', clue: 'Family' },
  { answer: 'KIT', clue: 'Tool set' },
  { answer: 'KIT', clue: 'Young fox' },
  { answer: 'LAB', clue: 'Science room' },
  { answer: 'LAB', clue: 'Test site' },
  { answer: 'LAD', clue: 'Young boy' },
  { answer: 'LAD', clue: 'Fellow' },
  { answer: 'LAG', clue: 'Fall behind' },
  { answer: 'LAG', clue: 'Delay' },
  { answer: 'LAP', clue: 'Race circuit' },
  { answer: 'LAP', clue: 'Sit upon, as a kitten' },
  { answer: 'LAW', clue: 'Statute' },
  { answer: 'LAW', clue: 'Attorney\'s field' },
  { answer: 'LAX', clue: 'SoCal airport code' },
  { answer: 'LAX', clue: 'Not strict' },
  { answer: 'LAY', clue: 'Place down' },
  { answer: 'LAY', clue: 'Non-clergy' },
  { answer: 'LED', clue: 'Was ahead' },
  { answer: 'LED', clue: 'Light type, briefly' },
  { answer: 'LEG', clue: 'Table support' },
  { answer: 'LEG', clue: 'Race segment' },
  { answer: 'LET', clue: 'Allow' },
  { answer: 'LET', clue: 'Tennis serve call' },
  { answer: 'LID', clue: 'Jar top' },
  { answer: 'LID', clue: 'Eye cover, slangily' },
  { answer: 'LIE', clue: 'Untruth' },
  { answer: 'LIE', clue: 'Recline' },
  { answer: 'LIP', clue: 'Mouth edge' },
  { answer: 'LIP', clue: 'Sass' },
  { answer: 'LOG', clue: 'Fireplace fuel' },
  { answer: 'LOG', clue: 'Record, as time' },
  { answer: 'LOT', clue: 'Parking area' },
  { answer: 'LOT', clue: 'Auction unit' },
  { answer: 'LOW', clue: 'Not high' },
  { answer: 'LOW', clue: 'Depressed' },
  { answer: 'MAD', clue: 'Angry' },
  { answer: 'MAD', clue: 'Magazine for satire' },
  { answer: 'MAN', clue: 'Fellow' },
  { answer: 'MAN', clue: 'Staff' },
  { answer: 'MAP', clue: 'Atlas page' },
  { answer: 'MAP', clue: 'Plan out' },
  { answer: 'MAT', clue: 'Welcome site' },
  { answer: 'MAT', clue: 'Yoga accessory' },
  { answer: 'MAW', clue: 'Gaping mouth' },
  { answer: 'MAW', clue: 'Big mouth' },
  { answer: 'MAY', clue: 'Spring month' },
  { answer: 'MAY', clue: 'Might' },
  { answer: 'MEN', clue: 'Guys' },
  { answer: 'MEN', clue: 'Restroom sign word' },
  { answer: 'MET', clue: 'Encountered' },
  { answer: 'MET', clue: 'NYC museum, with "the"' },
  { answer: 'MID', clue: 'Central prefix' },
  { answer: 'MID', clue: '___-Atlantic' },
  { answer: 'MIX', clue: 'Blend' },
  { answer: 'MIX', clue: 'Cake batter instruction' },
  { answer: 'MOB', clue: 'Angry crowd' },
  { answer: 'MOB', clue: 'Crime family' },
  { answer: 'MOM', clue: 'Family member' },
  { answer: 'MOM', clue: 'Mother, affectionately' },
  { answer: 'MOP', clue: 'Floor cleaner' },
  { answer: 'MOP', clue: 'Unruly hair' },
  { answer: 'MUD', clue: 'Wet dirt' },
  { answer: 'MUD', clue: 'Spa treatment ingredient' },
  { answer: 'MUG', clue: 'Coffee cup' },
  { answer: 'MUG', clue: 'Make faces for camera' },
  { answer: 'NAG', clue: 'Pester' },
  { answer: 'NAG', clue: 'Old horse' },
  { answer: 'NAP', clue: 'Short sleep' },
  { answer: 'NAP', clue: 'Soft fabric surface' },
  { answer: 'NET', clue: 'Fishing gear' },
  { answer: 'NET', clue: 'After taxes' },
  { answer: 'NEW', clue: 'Fresh' },
  { answer: 'NEW', clue: 'Just released' },
  { answer: 'NOD', clue: 'Silent agreement' },
  { answer: 'NOD', clue: 'Doze off' },
  { answer: 'NOR', clue: 'Neither partner' },
  { answer: 'NOR', clue: 'Scandinavian connector' },
  { answer: 'NOT', clue: 'Negation word' },
  { answer: 'NOT', clue: 'Prohibition word' },
  { answer: 'NOW', clue: 'This moment' },
  { answer: 'NOW', clue: 'Immediately' },
  { answer: 'NUT', clue: 'Almond or walnut' },
  { answer: 'NUT', clue: 'Enthusiast, slangily' },
  { answer: 'OAK', clue: 'Acorn producer' },
  { answer: 'OAK', clue: 'Sturdy wood' },
  { answer: 'OAR', clue: 'Rowboat implement' },
  { answer: 'OAR', clue: 'Crew team need' },
  { answer: 'ODD', clue: 'Strange' },
  { answer: 'ODD', clue: 'Not even' },
  { answer: 'OFF', clue: 'Not on' },
  { answer: 'OFF', clue: 'Away' },
  { answer: 'OIL', clue: 'Frying need' },
  { answer: 'OIL', clue: 'Crude export' },
  { answer: 'OLD', clue: 'Aged' },
  { answer: 'OLD', clue: 'Antique' },
  { answer: 'ONE', clue: 'Single digit' },
  { answer: 'ONE', clue: 'United' },
  { answer: 'OPT', clue: 'Choose' },
  { answer: 'OPT', clue: 'Decide' },
  { answer: 'ORB', clue: 'Sphere' },
  { answer: 'ORB', clue: 'Scepter companion' },
  { answer: 'ORE', clue: 'Raw metal source' },
  { answer: 'OUR', clue: 'Belonging to us' },
  { answer: 'OUR', clue: 'Shared possessive' },
  { answer: 'OUT', clue: 'Not in' },
  { answer: 'OUT', clue: 'Revealed, as a secret' },
  { answer: 'OWL', clue: 'Night hunter' },
  { answer: 'OWL', clue: 'Wise bird' },
  { answer: 'OWN', clue: 'Possess' },
  { answer: 'OWN', clue: 'Admit, with "up to"' },
  { answer: 'PAD', clue: 'Notebook' },
  { answer: 'PAD', clue: 'Helicopter landing site' },
  { answer: 'PAL', clue: 'Buddy' },
  { answer: 'PAL', clue: 'Friend' },
  { answer: 'PAN', clue: 'Skillet' },
  { answer: 'PAN', clue: 'Camera movement' },
  { answer: 'PAT', clue: 'Butter portion' },
  { answer: 'PAT', clue: 'Touch gently' },
  { answer: 'PAW', clue: 'Dog foot' },
  { answer: 'PAW', clue: 'Handle clumsily' },
  { answer: 'PAY', clue: 'Settle a bill' },
  { answer: 'PAY', clue: 'Salary' },
  { answer: 'PEA', clue: 'Pod vegetable' },
  { answer: 'PEA', clue: 'Small brain size, in slang' },
  { answer: 'PEG', clue: 'Coat hanger' },
  { answer: 'PEG', clue: 'Identify, slangily' },
  { answer: 'PEN', clue: 'Writing implement' },
  { answer: 'PEN', clue: 'Enclosure' },
  { answer: 'PET', clue: 'Furry friend' },
  { answer: 'PET', clue: 'Favorite' },
  { answer: 'PIE', clue: 'Dessert slice' },
  { answer: 'PIE', clue: 'Chart type' },
  { answer: 'PIG', clue: 'Farm animal' },
  { answer: 'PIG', clue: 'Hog' },
  { answer: 'PIN', clue: 'Bobby ___' },
  { answer: 'PIN', clue: 'Wrestling win' },
  { answer: 'PIT', clue: 'Peach center' },
  { answer: 'PIT', clue: 'Orchestra area' },
  { answer: 'POD', clue: 'Pea container' },
  { answer: 'POD', clue: 'Space capsule' },
  { answer: 'POP', clue: 'Soda, informally' },
  { answer: 'POP', clue: 'Burst' },
  { answer: 'POT', clue: 'Cooking vessel' },
  { answer: 'POT', clue: 'Jackpot' },
  { answer: 'PRO', clue: 'Expert' },
  { answer: 'PRO', clue: 'Paid athlete' },
  { answer: 'PRY', clue: 'Snoop' },
  { answer: 'PRY', clue: 'Lever open' },
  { answer: 'PUB', clue: 'British bar' },
  { answer: 'PUB', clue: 'Alehouse' },
  { answer: 'PUN', clue: 'Wordplay joke' },
  { answer: 'PUN', clue: 'Double meaning gag' },
  { answer: 'PUP', clue: 'Young dog' },
  { answer: 'PUP', clue: 'New recruit, slangily' },
  { answer: 'PUT', clue: 'Place' },
  { answer: 'PUT', clue: 'Golf stroke' },
  { answer: 'RAG', clue: 'Cleaning cloth' },
  { answer: 'RAG', clue: 'Tease' },
  { answer: 'RAM', clue: 'Bighorn sheep' },
  { answer: 'RAM', clue: 'Computer memory, briefly' },
  { answer: 'RAN', clue: 'Sprinted' },
  { answer: 'RAN', clue: 'Managed' },
  { answer: 'RAP', clue: 'Knock' },
  { answer: 'RAP', clue: 'Music genre' },
  { answer: 'RAT', clue: 'Lab animal' },
  { answer: 'RAT', clue: 'Informant, slangily' },
  { answer: 'RAW', clue: 'Uncooked' },
  { answer: 'RAW', clue: 'Unprocessed' },
  { answer: 'RAY', clue: 'Sunbeam' },
  { answer: 'RAY', clue: 'Flat fish' },
  { answer: 'RED', clue: 'Stop-sign color' },
  { answer: 'RED', clue: 'Wine choice' },
  { answer: 'RIB', clue: 'Barbecue cut' },
  { answer: 'RIB', clue: 'Tease' },
  { answer: 'RID', clue: 'Free from' },
  { answer: 'RID', clue: 'Get ___ of' },
  { answer: 'RIG', clue: 'Oil platform' },
  { answer: 'RIG', clue: 'Fix unfairly' },
  { answer: 'RIM', clue: 'Glass edge' },
  { answer: 'RIM', clue: 'Basketball hoop part' },
  { answer: 'RIP', clue: 'Tear' },
  { answer: 'RIP', clue: 'Tombstone letters' },
  { answer: 'ROB', clue: 'Steal from' },
  { answer: 'ROB', clue: 'Hold up' },
  { answer: 'ROD', clue: 'Fishing pole' },
  { answer: 'ROD', clue: 'Curtain holder' },
  { answer: 'ROT', clue: 'Decay' },
  { answer: 'ROT', clue: 'Go bad' },
  { answer: 'ROW', clue: 'Line of seats' },
  { answer: 'ROW', clue: 'Use oars' },
  { answer: 'RUB', clue: 'Massage' },
  { answer: 'RUB', clue: 'Apply, as salve' },
  { answer: 'RUG', clue: 'Floor covering' },
  { answer: 'RUG', clue: 'Toupee, slangily' },
  { answer: 'RUN', clue: 'Sprint' },
  { answer: 'RUN', clue: 'Stocking flaw' },
  { answer: 'RUT', clue: 'Groove' },
  { answer: 'RUT', clue: 'Boring routine' },
  { answer: 'RYE', clue: 'Deli bread type' },
  { answer: 'RYE', clue: 'Whiskey grain' },
  { answer: 'SAD', clue: 'Unhappy' },
  { answer: 'SAD', clue: 'Melancholy' },
  { answer: 'SAG', clue: 'Droop' },
  { answer: 'SAG', clue: 'Mattress problem' },
  { answer: 'SAP', clue: 'Tree fluid' },
  { answer: 'SAP', clue: 'Drain energy from' },
  { answer: 'SAT', clue: 'Was seated' },
  { answer: 'SAT', clue: 'College admission exam' },
  { answer: 'SAW', clue: 'Cutting tool' },
  { answer: 'SAW', clue: 'Old saying' },
  { answer: 'SAY', clue: 'Utter' },
  { answer: 'SAY', clue: 'For example' },
  { answer: 'SEA', clue: 'Ocean' },
  { answer: 'SEA', clue: 'Salty body' },
  { answer: 'SET', clue: 'Collection' },
  { answer: 'SET', clue: 'Tennis unit' },
  { answer: 'SEW', clue: 'Use a needle' },
  { answer: 'SEW', clue: 'Stitch' },
  { answer: 'SHE', clue: 'That woman' },
  { answer: 'SHE', clue: 'Pronoun' },
  { answer: 'SHY', clue: 'Bashful' },
  { answer: 'SHY', clue: 'Throw, as a horseshoe' },
  { answer: 'SIN', clue: 'Moral wrong' },
  { answer: 'SIN', clue: 'Transgression' },
  { answer: 'SIP', clue: 'Small drink' },
  { answer: 'SIP', clue: 'Nurse a drink' },
  { answer: 'SIR', clue: 'Knight title' },
  { answer: 'SIR', clue: 'Polite address' },
  { answer: 'SIT', clue: 'Take a chair' },
  { answer: 'SIT', clue: 'Pose for a portrait' },
  { answer: 'SIX', clue: 'Half a dozen' },
  { answer: 'SIX', clue: 'Evening hour, on a clock' },
  { answer: 'SKI', clue: 'Hit the slopes' },
  { answer: 'SKI', clue: 'Winter sport' },
  { answer: 'SKY', clue: 'Blue expanse' },
  { answer: 'SKY', clue: 'Limit, with "the"' },
  { answer: 'SLY', clue: 'Cunning' },
  { answer: 'SLY', clue: 'On the ___ (secretly)' },
  { answer: 'SOB', clue: 'Weep loudly' },
  { answer: 'SOB', clue: 'Cry' },
  { answer: 'SOD', clue: 'Lawn material' },
  { answer: 'SOD', clue: 'Turf' },
  { answer: 'SON', clue: 'Family boy' },
  { answer: 'SON', clue: 'Daughter\'s brother' },
  { answer: 'SOT', clue: 'Drunkard' },
  { answer: 'SOT', clue: 'Heavy drinker' },
  { answer: 'SOW', clue: 'Plant seeds' },
  { answer: 'SOW', clue: 'Female pig' },
  { answer: 'SOY', clue: 'Tofu source' },
  { answer: 'SOY', clue: 'Sauce type' },
  { answer: 'SPA', clue: 'Resort with massages' },
  { answer: 'SPA', clue: 'Mineral spring' },
  { answer: 'SPY', clue: 'Secret agent' },
  { answer: 'SPY', clue: 'Intelligence gatherer' },
  { answer: 'STY', clue: 'Pigpen' },
  { answer: 'STY', clue: 'Messy room' },
  { answer: 'SUB', clue: 'Sandwich type' },
  { answer: 'SUB', clue: 'Underwater vessel, briefly' },
  { answer: 'SUM', clue: 'Total' },
  { answer: 'SUM', clue: 'Addition result' },
  { answer: 'SUN', clue: 'Daylight source' },
  { answer: 'SUN', clue: 'Tanning need' },
  { answer: 'TAB', clue: 'Bar bill' },
  { answer: 'TAB', clue: 'Keyboard key' },
  { answer: 'TAD', clue: 'Smidge' },
  { answer: 'TAD', clue: 'Small amount' },
  { answer: 'TAG', clue: 'Price label' },
  { answer: 'TAG', clue: 'Playground game' },
  { answer: 'TAN', clue: 'Beach color' },
  { answer: 'TAN', clue: 'Light brown' },
  { answer: 'TAP', clue: 'Faucet' },
  { answer: 'TAP', clue: 'Light knock' },
  { answer: 'TAR', clue: 'Road surface' },
  { answer: 'TAR', clue: 'Paving material' },
  { answer: 'TEA', clue: 'Afternoon beverage' },
  { answer: 'TEA', clue: 'Earl Grey, e.g.' },
  { answer: 'TEN', clue: 'Decimal base' },
  { answer: 'TEN', clue: 'Perfect score, sometimes' },
  { answer: 'THE', clue: 'Definite article' },
  { answer: 'THE', clue: 'Not just any' },
  { answer: 'TIE', clue: 'Neckwear' },
  { answer: 'TIE', clue: 'Even score' },
  { answer: 'TIN', clue: 'Can material' },
  { answer: 'TIN', clue: 'Sn, chemically' },
  { answer: 'TIP', clue: 'Gratuity' },
  { answer: 'TIP', clue: 'Helpful hint' },
  { answer: 'TOE', clue: 'Foot digit' },
  { answer: 'TOE', clue: 'Ballet point' },
  { answer: 'TON', clue: 'Heavy weight' },
  { answer: 'TON', clue: 'Large amount, informally' },
  { answer: 'TOO', clue: 'Also' },
  { answer: 'TOO', clue: 'Overly' },
  { answer: 'TOP', clue: 'Summit' },
  { answer: 'TOP', clue: 'Spinning toy' },
  { answer: 'TOT', clue: 'Little kid' },
  { answer: 'TOT', clue: 'Small child' },
  { answer: 'TOW', clue: 'Haul away' },
  { answer: 'TOW', clue: 'Pull behind' },
  { answer: 'TOY', clue: 'Plaything' },
  { answer: 'TOY', clue: 'Small dog breed' },
  { answer: 'TRY', clue: 'Attempt' },
  { answer: 'TRY', clue: 'Give it a shot' },
  { answer: 'TUB', clue: 'Bath fixture' },
  { answer: 'TUB', clue: 'Large container' },
  { answer: 'TUG', clue: 'Pull hard' },
  { answer: 'TUG', clue: 'Harbor boat' },
  { answer: 'TWO', clue: 'Pair count' },
  { answer: 'TWO', clue: 'Company number' },
  { answer: 'URN', clue: 'Large vase' },
  { answer: 'URN', clue: 'Caterer\'s coffee holder' },
  { answer: 'USE', clue: 'Employ' },
  { answer: 'USE', clue: 'Put to work' },
  { answer: 'VAN', clue: 'Moving truck' },
  { answer: 'VAN', clue: 'Minivan, e.g.' },
  { answer: 'VAT', clue: 'Large brewing tub' },
  { answer: 'VAT', clue: 'Industrial container' },
  { answer: 'VET', clue: 'Animal doctor' },
  { answer: 'VET', clue: 'Check thoroughly' },
  { answer: 'VIA', clue: 'By way of' },
  { answer: 'VIA', clue: 'Through' },
  { answer: 'VIE', clue: 'Compete' },
  { answer: 'VIE', clue: 'Contend' },
  { answer: 'VOW', clue: 'Solemn promise' },
  { answer: 'VOW', clue: 'Wedding exchange' },
  { answer: 'WAR', clue: 'Armed conflict' },
  { answer: 'WAR', clue: 'Card game' },
  { answer: 'WAS', clue: 'Used to be' },
  { answer: 'WAS', clue: 'Past tense of "is"' },
  { answer: 'WAX', clue: 'Candle material' },
  { answer: 'WAX', clue: 'Polish, as a floor' },
  { answer: 'WAY', clue: 'Method' },
  { answer: 'WAY', clue: 'Path' },
  { answer: 'WEB', clue: 'Spider creation' },
  { answer: 'WEB', clue: 'Internet, with "the"' },
  { answer: 'WED', clue: 'Married' },
  { answer: 'WED', clue: 'Middle of the week, briefly' },
  { answer: 'WET', clue: 'Soaked' },
  { answer: 'WET', clue: 'Not dry' },
  { answer: 'WHO', clue: 'Which person' },
  { answer: 'WHO', clue: 'Question word' },
  { answer: 'WHY', clue: 'Reason-seeking word' },
  { answer: 'WHY', clue: 'Question word' },
  { answer: 'WIG', clue: 'Judge\'s wear, once' },
  { answer: 'WIG', clue: 'Costume hairpiece' },
  { answer: 'WIN', clue: 'Take first place' },
  { answer: 'WIN', clue: 'Victory' },
  { answer: 'WIT', clue: 'Clever humor' },
  { answer: 'WIT', clue: 'Intelligence' },
  { answer: 'WOE', clue: 'Misery' },
  { answer: 'WOE', clue: 'Sorrow' },
  { answer: 'WOK', clue: 'Stir-fry pan' },
  { answer: 'WOK', clue: 'Asian cooking vessel' },
  { answer: 'WON', clue: 'Achieved victory' },
  { answer: 'WON', clue: 'Korean currency' },
  { answer: 'WOO', clue: 'Court romantically' },
  { answer: 'WOO', clue: 'Seek affection' },
  { answer: 'WOW', clue: 'Amaze' },
  { answer: 'WOW', clue: 'Exclamation of wonder' },
  { answer: 'YAK', clue: 'Tibetan bovine' },
  { answer: 'YAK', clue: 'Talk endlessly' },
  { answer: 'YAM', clue: 'Thanksgiving tuber' },
  { answer: 'YAM', clue: 'Orange root vegetable' },
  { answer: 'YAP', clue: 'Talk incessantly' },
  { answer: 'YAP', clue: 'Small dog\'s bark' },
  { answer: 'YAW', clue: 'Deviate off course' },
  { answer: 'YAW', clue: 'Swerve' },
  { answer: 'YEA', clue: 'Affirmative vote' },
  { answer: 'YEA', clue: 'Vote for' },
  { answer: 'YES', clue: 'Affirmative' },
  { answer: 'YES', clue: 'Agreement' },
  { answer: 'YET', clue: 'Still' },
  { answer: 'YET', clue: 'Thus far' },
  { answer: 'YEW', clue: 'Bow wood' },
  { answer: 'YEW', clue: 'Evergreen tree' },
  { answer: 'YOU', clue: 'Second person' },
  { answer: 'YOU', clue: 'The one reading this' },
  { answer: 'ZAP', clue: 'Microwave, slangily' },
  { answer: 'ZAP', clue: 'Eliminate quickly' },
  { answer: 'ZEN', clue: 'Meditation discipline' },
  { answer: 'ZEN', clue: 'Calm state' },
  { answer: 'ZIP', clue: 'Postal code, informally' },
  { answer: 'ZIP', clue: 'Move quickly' },
  { answer: 'ZOO', clue: 'Animal park' },
  { answer: 'ZOO', clue: 'Chaotic place, metaphorically' },
  { answer: 'CROSSWORD', clue: 'Puzzle with interlocking words' },
  { answer: 'THEME', clue: 'Unifying puzzle concept' },
  { answer: 'FILL', clue: 'Non-theme answers' },
  { answer: 'GRID', clue: 'Puzzle layout' },
  { answer: 'CLUE', clue: 'Hint for an answer' },
  { answer: 'BLACK', clue: 'Unused grid square' },
  { answer: 'WHITE', clue: 'Letter square' },
  { answer: 'ACROSS', clue: 'Horizontal direction' },
  { answer: 'DOWN', clue: 'Vertical direction' },
  { answer: 'REBUS', clue: 'Multi-letter single cell' },
  { answer: 'SYMMETRY', clue: '180° rotational balance' },
  { answer: 'INTERLOCK', clue: 'All white cells connected' },
  { answer: 'CONSTRUCTOR', clue: 'Puzzle maker' },
  { answer: 'EDITOR', clue: 'Publication puzzle reviewer' },
  { answer: 'SUBMIT', clue: 'Send to an editor' },
  { answer: 'PUZ', clue: 'Across Lite file extension' },
  { answer: 'LAT', clue: 'Long. partner' },
  { answer: 'LON', clue: 'Lat. partner' },
  { answer: 'GPS', clue: 'Navigation aid, briefly' },
  { answer: 'ATM', clue: 'Cash dispenser' },
  { answer: 'NBA', clue: 'Hoops league, briefly' },
  { answer: 'NFL', clue: 'Super Bowl org.' },
  { answer: 'MLB', clue: 'World Series org.' },
  { answer: 'CIA', clue: 'Spy org.' },
  { answer: 'FBI', clue: 'Federal investigators' },
  { answer: 'USA', clue: 'Stars and Stripes land' },
  { answer: 'UK', clue: 'Britain, briefly' },
  { answer: 'EU', clue: 'Continental bloc, briefly' },
  { answer: 'UN', clue: 'Global peace org.' },
  { answer: 'TV', clue: 'Living room screen, for short' },
  { answer: 'PC', clue: 'Desktop machine, briefly' },
  { answer: 'AI', clue: 'ChatGPT tech, briefly' },
  { answer: 'OS', clue: 'Windows or macOS, briefly' },
  { answer: 'ID', clue: 'Driver\'s license, e.g.' },
  { answer: 'OK', clue: 'Fine' },
  { answer: 'HI', clue: 'Aloha State' },
  { answer: 'MA', clue: 'Bay State, briefly' },
  { answer: 'CA', clue: 'Golden State, briefly' },
  { answer: 'NY', clue: 'Empire State, briefly' },
  { answer: 'TX', clue: 'Lone Star State, briefly' },
  { answer: 'FL', clue: 'Sunshine State, briefly' },
  { answer: 'PA', clue: 'Keystone State, briefly' },
  { answer: 'OH', clue: 'Buckeye State, briefly' },
  { answer: 'IL', clue: 'Land of Lincoln, briefly' },
  { answer: 'GA', clue: 'Peach State, briefly' },
  { answer: 'NC', clue: 'Tar Heel State, briefly' },
  { answer: 'MI', clue: 'Great Lakes State, briefly' },
  { answer: 'NJ', clue: 'Garden State, briefly' },
  { answer: 'VA', clue: 'Old Dominion, briefly' },
  { answer: 'WA', clue: 'Evergreen State, briefly' },
  { answer: 'AZ', clue: 'Grand Canyon State, briefly' },
  { answer: 'CO', clue: 'Rocky Mountain State, briefly' },
  { answer: 'OR', clue: 'Beaver State, briefly' },
  { answer: 'MN', clue: 'Land of 10,000 Lakes, briefly' },
  { answer: 'WI', clue: 'Badger State, briefly' },
  { answer: 'MO', clue: 'Show Me State, briefly' },
  { answer: 'TN', clue: 'Volunteer State, briefly' },
  { answer: 'IN', clue: 'Hoosier State, briefly' },
  { answer: 'MD', clue: 'Old Line State, briefly' },
  { answer: 'CT', clue: 'Constitution State, briefly' },
  { answer: 'SC', clue: 'Palmetto State, briefly' },
  { answer: 'AL', clue: 'Yellowhammer State, briefly' },
  { answer: 'LA', clue: 'Pelican State, briefly' },
  { answer: 'KY', clue: 'Bluegrass State, briefly' },
  { answer: 'UT', clue: 'Beehive State, briefly' },
  { answer: 'IA', clue: 'Hawkeye State, briefly' },
  { answer: 'NV', clue: 'Silver State, briefly' },
  { answer: 'AR', clue: 'Natural State, briefly' },
  { answer: 'MS', clue: 'Magnolia State, briefly' },
  { answer: 'KS', clue: 'Sunflower State, briefly' },
  { answer: 'NM', clue: 'Land of Enchantment, briefly' },
  { answer: 'NE', clue: 'Cornhusker State, briefly' },
  { answer: 'WV', clue: 'Mountain State, briefly' },
  { answer: 'ID', clue: 'Gem State, briefly' },
  { answer: 'HI', clue: 'Aloha State, briefly' },
  { answer: 'NH', clue: 'Granite State, briefly' },
  { answer: 'ME', clue: 'Pine Tree State, briefly' },
  { answer: 'RI', clue: 'Ocean State, briefly' },
  { answer: 'MT', clue: 'Treasure State, briefly' },
  { answer: 'DE', clue: 'First State, briefly' },
  { answer: 'SD', clue: 'Mount Rushmore State, briefly' },
  { answer: 'ND', clue: 'Peace Garden State, briefly' },
  { answer: 'AK', clue: 'Last Frontier, briefly' },
  { answer: 'VT', clue: 'Green Mountain State, briefly' },
  { answer: 'WY', clue: 'Equality State, briefly' },
  { answer: 'DC', clue: 'Capital initials' },
  { answer: 'PR', clue: 'San Juan\'s island, briefly' },
  { answer: 'VI', clue: 'St. Thomas locale, briefly' },
  { answer: 'GU', clue: 'Pacific territory, briefly' },
  { answer: 'AS', clue: 'Pago Pago locale, briefly' },
  { answer: 'MP', clue: 'Saipan locale, briefly' },
  { answer: 'UM', clue: 'Minor outlying islands, briefly' },
]

export function searchClues(answer: string): ClueRecord[] {
  const q = answer.trim().toUpperCase()
  if (!q) return []
  return CLUE_DATASET.filter((c) => c.answer === q)
}
