#!/usr/bin/env node
/**
 * Generates public/data/words.json — a curated crossword word list with scores and tags.
 * Run: node scripts/generate-words.mjs
 */
import { writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { scoreWordByLength } from './wordScoring.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = join(__dirname, '../public/data')
mkdirSync(outDir, { recursive: true })

const crosswordese = new Set([
  'ETUI', 'OLEO', 'ERNE', 'ESNE', 'ADIT', 'ALEE', 'ARIL', 'ASTA', 'ECRU', 'EMEU',
  'ENOL', 'ERST', 'ETNA', 'EWER', 'GAOL', 'GAMY', 'GAM', 'GAR', 'GEE', 'GHI',
  'GIB', 'GINK', 'GOB', 'GOY', 'GUV', 'HADJ', 'HADJ', 'HORA', 'IDEA', 'ILEX',
  'ILIA', 'INRO', 'ISBA', 'ITAS', 'KEPI', 'KOLA', 'KOP', 'LWEI', 'MAAR', 'MAGS',
  'MEER', 'MEGS', 'MENG', 'MESH', 'MOAS', 'NAOI', 'NAPE', 'NEAP', 'NEEM', 'NEVI',
  'NISI', 'NOIL', 'NTH', 'OAFS', 'OBIA', 'OBIS', 'OCAS', 'OGEE', 'OGRE', 'OHIA',
  'OHMS', 'OKRA', 'OLEA', 'OMER', 'ONER', 'ONTO', 'ORAD', 'ORCA', 'ORFE', 'ORLE',
  'OSAR', 'OTIC', 'OVUM', 'OXEN', 'OXES', 'PAHS', 'PFFT', 'PHIS', 'PIPS', 'PLIE',
  'POET', 'PORE', 'PROA', 'PSST', 'PTUI', 'PUJA', 'QUAD', 'QUAY', 'QUID', 'QUIN',
  'RAIA', 'RAIS', 'RAJA', 'RAMI', 'RANI', 'RAPE', 'RARE', 'RATA', 'RAWS', 'REIS',
  'REMS', 'REOS', 'REPO', 'RETE', 'RHEA', 'RIME', 'ROES', 'ROTA', 'ROTE', 'ROUE',
  'ROVE', 'RUBS', 'RUES', 'RUGA', 'RUIN', 'RUSE', 'RUTS', 'RYAS', 'RYES', 'SAIC',
  'SAGA', 'SAGO', 'SAKE', 'SALE', 'SAME', 'SANE', 'SANG', 'SANK', 'SANS', 'SAPS',
  'SARI', 'SATE', 'SAVE', 'SCAD', 'SCAM', 'SCAN', 'SCAR', 'SCAT', 'SCOP', 'SCOT',
  'SCOW', 'SCUD', 'SCUM', 'SCUT', 'SEAL', 'SEAM', 'SEAR', 'SEAS', 'SEAT', 'SECS',
  'SEED', 'SEEK', 'SEEM', 'SEEN', 'SEEP', 'SEER', 'SEES', 'SEGO', 'SEGS', 'SEIS',
  'SELA', 'SELL', 'SEMI', 'SEND', 'SENE', 'SENS', 'SENT', 'SEPT', 'SERA', 'SERE',
  'SERF', 'SERS', 'SESS', 'SETA', 'SETS', 'SEWN', 'SEWS', 'SEXT', 'SEXY', 'SHAD',
  'AGAR', 'ALAR', 'ALBA', 'ALBS', 'ALEC', 'ALEE', 'ALFA', 'ALGA', 'ALIF', 'ALIT',
  'ALMS', 'ALOE', 'ALOW', 'ALPS', 'ALSO', 'ALTO', 'ALUM', 'AMAH', 'AMAS', 'AMBO',
  'AMEN', 'AMIA', 'AMID', 'AMIE', 'AMIN', 'AMIR', 'AMIS', 'AMMO', 'AMOK', 'AMOS',
  'AMP', 'AMPS', 'AMUS', 'ANAS', 'ANDS', 'ANES', 'ANIL', 'ANIS', 'ANNA', 'ANOA',
  'ANON', 'ANSA', 'ANTA', 'ANTE', 'ANTI', 'ANTS', 'ANUS', 'APED', 'APER', 'APES',
  'APEX', 'APOD', 'APOS', 'APPS', 'APSE', 'APSO', 'AQUA', 'ARAK', 'ARBS', 'ARCH',
  'ARCO', 'ARCS', 'AREA', 'ARES', 'ARFS', 'ARIA', 'ARID', 'ARIL', 'ARKS', 'ARLE',
  'ARMS', 'ARMY', 'ARNA', 'AROW', 'ARPA', 'ARSY', 'ARTS', 'ARTY', 'ARUM', 'ARVO',
  'ARYL', 'ASCI', 'ASEA', 'ASHY', 'ASKS', 'ASPS', 'ATAP', 'ATES', 'ATMA', 'ATOM',
  'ATOP', 'ATUA', 'AUFS', 'AUKS', 'AULA', 'AULD', 'AUNT', 'AURA', 'AUTO', 'AVER',
  'AVES', 'AVID', 'AVOS', 'AVOW', 'AWAY', 'AWED', 'AWEE', 'AWES', 'AWLS', 'AWNS',
  'AWNY', 'AWOL', 'AWRY', 'AXAL', 'AXED', 'AXEL', 'AXES', 'AXIL', 'AXIS', 'AXLE',
  'AXON', 'AYAH', 'AYES', 'AYIN', 'AZAN', 'AZON', 'BAAL', 'BAAS', 'BABA', 'BABE',
  'BABU', 'BABY', 'BACH', 'BACK', 'BADE', 'BADS', 'BAEL', 'BAFF', 'BAFT', 'BAGS',
  'BAHT', 'BAIL', 'BAIT', 'BAKE', 'BALD', 'BALE', 'BALK', 'BALL', 'BALM', 'BALS',
  'BALU', 'BAMS', 'BANC', 'BAND', 'BANE', 'BANG', 'BANI', 'BANK', 'BANS', 'BAOS',
  'BAPS', 'BARB', 'BARD', 'BARE', 'BARF', 'BARK', 'BARM', 'BARN', 'BARP', 'BARS',
  'BASE', 'BASH', 'BASK', 'BASS', 'BAST', 'BATE', 'BATH', 'BATS', 'BATT', 'BAUD',
  'BAUK', 'BAWL', 'BAWN', 'BAWR', 'BAYE', 'BAYS', 'BAYT', 'BAZA', 'BEAD', 'BEAK',
  'BEAM', 'BEAN', 'BEAR', 'BEAT', 'BEAU', 'BECK', 'BEDE', 'BEDS', 'BEDU', 'BEEF',
  'BEEN', 'BEEP', 'BEER', 'BEES', 'BEET', 'BEGS', 'BEIN', 'BELL', 'BELS', 'BELT',
  'BEMA', 'BEND', 'BENE', 'BENI', 'BENJ', 'BENS', 'BENT', 'BERG', 'BERK', 'BERM',
  'BEST', 'BETA', 'BETH', 'BETS', 'BEVY', 'BEYS', 'BHAI', 'BHEL', 'BHUT', 'BIAS',
  'BIBB', 'BIBS', 'BICE', 'BIDE', 'BIDI', 'BIDS', 'BIEN', 'BIER', 'BIFF', 'BIFS',
  'BIGA', 'BIGG', 'BIGS', 'BIKE', 'BILE', 'BILK', 'BILL', 'BIMA', 'BIND', 'BINE',
  'BING', 'BINK', 'BINS', 'BINT', 'BIOS', 'BIRD', 'BIRK', 'BIRL', 'BIRO', 'BIRR',
  'BISE', 'BISH', 'BISK', 'BITE', 'BITO', 'BITS', 'BITT', 'BIZE', 'BLAB', 'BLAD',
  'BLAE', 'BLAG', 'BLAH', 'BLAM', 'BLAT', 'BLAW', 'BLAY', 'BLEB', 'BLED', 'BLEE',
  'BLET', 'BLEW', 'BLEY', 'BLIN', 'BLIP', 'BLIT', 'BLOB', 'BLOC', 'BLOG', 'BLOT',
  'BLOW', 'BLUB', 'BLUE', 'BLUR', 'BOAB', 'BOAK', 'BOAR', 'BOAS', 'BOAT', 'BOBA',
  'BOBO', 'BOBS', 'BOCK', 'BODE', 'BODS', 'BODY', 'BOEP', 'BOET', 'BOFF', 'BOGS',
  'BOGY', 'BOHO', 'BOHS', 'BOIL', 'BOIS', 'BOKE', 'BOKO', 'BOKS', 'BOLA', 'BOLD',
  'BOLE', 'BOLL', 'BOLO', 'BOLT', 'BOMA', 'BOMB', 'BONA', 'BOND', 'BONE', 'BONG',
  'BONK', 'BONY', 'BOOB', 'BOOH', 'BOOK', 'BOOL', 'BOOM', 'BOON', 'BOOR', 'BOOS',
  'BOOT', 'BOPS', 'BORA', 'BORD', 'BORE', 'BORK', 'BORM', 'BORN', 'BORS', 'BORT',
  'BOSH', 'BOSK', 'BOSS', 'BOTA', 'BOTH', 'BOTS', 'BOUK', 'BOUN', 'BOUT', 'BOWL',
  'BOWR', 'BOWS', 'BOXY', 'BOYA', 'BOYO', 'BOYS', 'BOZO', 'BRAD', 'BRAE', 'BRAG',
  'BRAK', 'BRAN', 'BRAS', 'BRAT', 'BRAW', 'BRAY', 'BRED', 'BREE', 'BREI', 'BREN',
  'BRER', 'BREW', 'BREY', 'BRIE', 'BRIG', 'BRIK', 'BRIM', 'BRIN', 'BRIO', 'BRIS',
  'BRIT', 'BROD', 'BROG', 'BROK', 'BROO', 'BROS', 'BROW', 'BRRR', 'BRUS', 'BRUT',
  'BRUX', 'BRYS', 'BUAT', 'BUBA', 'BUBS', 'BUBU', 'BUCK', 'BUDA', 'BUDI', 'BUDO',
  'BUDS', 'BUFF', 'BUFO', 'BUGS', 'BUHL', 'BUHR', 'BULB', 'BULK', 'BULL', 'BUMF',
  'BUMP', 'BUMS', 'BUNA', 'BUND', 'BUNG', 'BUNK', 'BUNN', 'BUNS', 'BUNT', 'BUOY',
  'BURA', 'BURD', 'BURG', 'BURK', 'BURL', 'BURN', 'BURP', 'BURR', 'BURS', 'BURY',
  'BUSH', 'BUSK', 'BUSS', 'BUST', 'BUSY', 'BUTS', 'BUTT', 'BUYS', 'BUZZ', 'BYDE',
  'BYES', 'BYKE', 'BYRE', 'BYRL', 'BYTE', 'CAAS', 'CABA', 'CABS', 'CACA', 'CADE',
  'CADI', 'CADS', 'CAFE', 'CAFF', 'CAFS', 'CAGE', 'CAGS', 'CAGY', 'CAID', 'CAIN',
  'CAKE', 'CAKY', 'CALF', 'CALK', 'CALL', 'CALM', 'CALO', 'CALP', 'CALS', 'CALX',
  'CAMA', 'CAME', 'CAMI', 'CAMO', 'CAMP', 'CAMS', 'CANA', 'CAND', 'CANE', 'CANG',
  'CANS', 'CANT', 'CAPA', 'CAPE', 'CAPH', 'CAPI', 'CAPO', 'CAPS', 'CARB', 'CARD',
  'CARE', 'CARK', 'CARL', 'CARN', 'CARP', 'CARR', 'CARS', 'CART', 'CASA', 'CASE',
  'CASH', 'CASK', 'CAST', 'CATE', 'CATS', 'CAUF', 'CAUK', 'CAUL', 'CAUM', 'CAUP',
  'CAVA', 'CAVE', 'CAVS', 'CAWK', 'CAWS', 'CAYS', 'CEAS', 'CECA', 'CEDE', 'CEDI',
  'CEES', 'CEIL', 'CELL', 'CELT', 'CENS', 'CENT', 'CEPE', 'CEPS', 'CERE', 'CERO',
  'CERT', 'CESS', 'CETE', 'CHAD', 'CHAI', 'CHAL', 'CHAM', 'CHAO', 'CHAP', 'CHAR',
  'CHAT', 'CHAV', 'CHAW', 'CHAY', 'CHEF', 'CHEM', 'CHER', 'CHES', 'CHET', 'CHEW',
  'CHEZ', 'CHIA', 'CHIB', 'CHIC', 'CHID', 'CHIN', 'CHIP', 'CHIS', 'CHIT', 'CHIV',
  'CHOG', 'CHON', 'CHOP', 'CHOU', 'CHOW', 'CHUB', 'CHUG', 'CHUM', 'CHUT', 'CIAO',
  'CIBS', 'CIDE', 'CIDS', 'CIEL', 'CIGS', 'CILL', 'CINE', 'CION', 'CIRE', 'CIRL',
  'CIST', 'CITE', 'CITS', 'CITY', 'CIVE', 'CLAD', 'CLAG', 'CLAM', 'CLAN', 'CLAP',
  'CLAT', 'CLAW', 'CLAY', 'CLEF', 'CLEG', 'CLEM', 'CLEW', 'CLIP', 'CLIT', 'CLOD',
  'CLOG', 'CLON', 'CLOP', 'CLOT', 'CLOU', 'CLOW', 'CLOY', 'CLUB', 'CLUE', 'CLUG',
  'COAL', 'COAT', 'COAX', 'COBB', 'COBS', 'COCA', 'COCH', 'COCK', 'COCO', 'CODA',
  'CODE', 'CODS', 'COED', 'COFF', 'COFT', 'COGS', 'COHO', 'COIF', 'COIL', 'COIN',
  'COIR', 'COIT', 'COKE', 'COKY', 'COLA', 'COLD', 'COLE', 'COLL', 'COLS', 'COLT',
  'COLY', 'COMA', 'COMB', 'COME', 'COMM', 'COMP', 'COMS', 'CONE', 'CONF', 'CONI',
  'CONK', 'CONN', 'CONS', 'CONY', 'COOF', 'COOK', 'COOL', 'COOM', 'COON', 'COOP',
  'COOS', 'COOT', 'COPE', 'COPS', 'COPY', 'CORD', 'CORE', 'CORF', 'CORK', 'CORM',
  'CORN', 'CORS', 'CORY', 'COSE', 'COSH', 'COSS', 'COST', 'COSY', 'COTE', 'COTS',
  'COTT', 'COUP', 'COUR', 'COVE', 'COWK', 'COWL', 'COWP', 'COWS', 'COWY', 'COXA',
  'COXY', 'COYS', 'COZE', 'COZY', 'CRAB', 'CRAG', 'CRAM', 'CRAN', 'CRAP', 'CRAW',
  'CRAY', 'CRED', 'CREE', 'CREM', 'CREW', 'CRIB', 'CRIM', 'CRIS', 'CRIT', 'CROC',
  'CROG', 'CROP', 'CROW', 'CRUD', 'CRUE', 'CRUS', 'CRUX', 'CUBS', 'CUDS', 'CUED',
  'CUES', 'CUFF', 'CUIF', 'CUKE', 'CULL', 'CULM', 'CULT', 'CUMS', 'CUNT', 'CUPS',
  'CURB', 'CURD', 'CURE', 'CURF', 'CURL', 'CURN', 'CURR', 'CURS', 'CURT', 'CUSH',
  'CUSK', 'CUSP', 'CUSS', 'CUTE', 'CUTS', 'CWMS', 'CYAN', 'CYMA', 'CYME', 'CYST',
  'CYTE', 'CZAR', 'DAAL', 'DABS', 'DACE', 'DACK', 'DADA', 'DADO', 'DADS', 'DAES',
  'DAFF', 'DAFT', 'DAGO', 'DAGS', 'DAHL', 'DAHS', 'DAIL', 'DAIS', 'DAKS', 'DALE',
  'DALI', 'DALS', 'DALT', 'DAME', 'DAMP', 'DAMS', 'DANG', 'DANK', 'DANS', 'DANT',
  'DAPS', 'DARB', 'DARE', 'DARG', 'DARK', 'DARN', 'DART', 'DASH', 'DATA', 'DATE',
  'DATO', 'DAUB', 'DAUD', 'DAUR', 'DAUT', 'DAVY', 'DAWD', 'DAWK', 'DAWN', 'DAWS',
  'DAWT', 'DAYS', 'DAZE', 'DEAD', 'DEAF', 'DEAL', 'DEAN', 'DEAR', 'DEAW', 'DEBE',
  'DEBS', 'DEBT', 'DECK', 'DECO', 'DEED', 'DEEK', 'DEEM', 'DEEN', 'DEEP', 'DEER',
  'DEES', 'DEET', 'DEFI', 'DEFO', 'DEFT', 'DEFY', 'DEGS', 'DEID', 'DEIF', 'DEIL',
  'DEKE', 'DELE', 'DELF', 'DELI', 'DELL', 'DELO', 'DELS', 'DELT', 'DEME', 'DEMO',
  'DEMY', 'DENE', 'DENI', 'DENS', 'DENT', 'DENY', 'DERE', 'DERM', 'DERN', 'DERO',
  'DERV', 'DESI', 'DESK', 'DEUS', 'DEVA', 'DEVS', 'DEWS', 'DEWY', 'DEXY', 'DEYS',
  'DHAK', 'DHAL', 'DHOL', 'DHOW', 'DIAL', 'DIBS', 'DICE', 'DICH', 'DICK', 'DICT',
  'DIDO', 'DIDY', 'DIEB', 'DIED', 'DIEL', 'DIES', 'DIET', 'DIFF', 'DIFS', 'DIGS',
  'DIKA', 'DIKE', 'DILL', 'DIME', 'DIMP', 'DIMS', 'DINE', 'DING', 'DINK', 'DINO',
  'DINS', 'DINT', 'DIOL', 'DIPS', 'DIPT', 'DIRE', 'DIRK', 'DIRL', 'DIRT', 'DISA',
  'DISC', 'DISH', 'DISK', 'DISS', 'DITA', 'DITE', 'DITS', 'DITT', 'DITZ', 'DIVA',
  'DIVE', 'DIVI', 'DIVS', 'DIXI', 'DIXY', 'DJIN', 'DOAB', 'DOAT', 'DOBE', 'DOBS',
  'DOBY', 'DOCK', 'DOCO', 'DOCS', 'DODO', 'DODS', 'DOEK', 'DOEN', 'DOER', 'DOES',
  'DOFF', 'DOGE', 'DOGS', 'DOGY', 'DOHS', 'DOIT', 'DOJO', 'DOLE', 'DOLL', 'DOLS',
  'DOLT', 'DOME', 'DOMS', 'DOMY', 'DONA', 'DONE', 'DONS', 'DOOB', 'DOOK', 'DOOL',
  'DOOM', 'DOON', 'DOOR', 'DOOS', 'DOPA', 'DOPE', 'DOPS', 'DOPY', 'DORB', 'DORE',
  'DORK', 'DORM', 'DORP', 'DORR', 'DORS', 'DORT', 'DORY', 'DOSE', 'DOSH', 'DOSS',
  'DOST', 'DOTE', 'DOTH', 'DOTS', 'DOTY', 'DOUC', 'DOUK', 'DOUM', 'DOUP', 'DOUX',
  'DOVE', 'DOWN', 'DOWP', 'DOWS', 'DOWT', 'DOXY', 'DOYS', 'DOZE', 'DOZY', 'DRAB',
  'DRAC', 'DRAD', 'DRAG', 'DRAM', 'DRAP', 'DRAT', 'DRAW', 'DRAY', 'DREE', 'DREG',
  'DREK', 'DREW', 'DREY', 'DRIB', 'DRIP', 'DROP', 'DROW', 'DRUB', 'DRUG', 'DRUM',
  'DRYS', 'DSOS', 'DUAD', 'DUAL', 'DUAN', 'DUAR', 'DUBS', 'DUCE', 'DUCI', 'DUCK',
  'DUCT', 'DUDE', 'DUDS', 'DUEL', 'DUES', 'DUET', 'DUFF', 'DUGS', 'DUKE', 'DULE',
  'DULL', 'DULY', 'DUMA', 'DUMB', 'DUMP', 'DUNE', 'DUNG', 'DUNK', 'DUNS', 'DUNT',
  'DUOS', 'DUPE', 'DUPS', 'DURA', 'DURE', 'DURN', 'DURO', 'DURR', 'DUSH', 'DUSK',
  'DUST', 'DUTY', 'DWAM', 'DYAD', 'DYED', 'DYER', 'DYES', 'DYKE', 'DYNE', 'DZOS',
])

const properNouns = {
  OBAMA: ['proper_noun', 'domain:politics'],
  TRUMP: ['proper_noun', 'domain:politics'],
  BIDEN: ['proper_noun', 'domain:politics'],
  CLINTON: ['proper_noun', 'domain:politics'],
  REAGAN: ['proper_noun', 'domain:politics'],
  KENNEDY: ['proper_noun', 'domain:politics'],
  LINCOLN: ['proper_noun', 'domain:politics'],
  WASHINGTON: ['proper_noun', 'domain:politics'],
  JEFFERSON: ['proper_noun', 'domain:politics'],
  ROOSEVELT: ['proper_noun', 'domain:politics'],
  EINSTEIN: ['proper_noun', 'domain:science'],
  NEWTON: ['proper_noun', 'domain:science'],
  DARWIN: ['proper_noun', 'domain:science'],
  GALILEO: ['proper_noun', 'domain:science'],
  TESLA: ['proper_noun', 'domain:science'],
  EDISON: ['proper_noun', 'domain:science'],
  SHAKESPEARE: ['proper_noun', 'domain:literature'],
  DICKENS: ['proper_noun', 'domain:literature'],
  HEMINGWAY: ['proper_noun', 'domain:literature'],
  TWAIN: ['proper_noun', 'domain:literature'],
  BEETHOVEN: ['proper_noun', 'domain:music'],
  MOZART: ['proper_noun', 'domain:music'],
  BACH: ['proper_noun', 'domain:music'],
  CHOPIN: ['proper_noun', 'domain:music'],
  ELVIS: ['proper_noun', 'domain:music'],
  BEATLES: ['proper_noun', 'domain:music'],
  JORDAN: ['proper_noun', 'domain:sports'],
  BRADY: ['proper_noun', 'domain:sports'],
  RUTH: ['proper_noun', 'domain:sports'],
  ALI: ['proper_noun', 'domain:sports'],
  WOODS: ['proper_noun', 'domain:sports'],
  FEDERER: ['proper_noun', 'domain:sports'],
  NADAL: ['proper_noun', 'domain:sports'],
  SERENA: ['proper_noun', 'domain:sports'],
  LEBRON: ['proper_noun', 'domain:sports'],
  KOBE: ['proper_noun', 'domain:sports'],
  SHAQ: ['proper_noun', 'domain:sports'],
  PELE: ['proper_noun', 'domain:sports'],
  MARADONA: ['proper_noun', 'domain:sports'],
  MESSI: ['proper_noun', 'domain:sports'],
  RONALDO: ['proper_noun', 'domain:sports'],
  PARIS: ['proper_noun', 'domain:geography'],
  LONDON: ['proper_noun', 'domain:geography'],
  TOKYO: ['proper_noun', 'domain:geography'],
  ROME: ['proper_noun', 'domain:geography'],
  CAIRO: ['proper_noun', 'domain:geography'],
  SYDNEY: ['proper_noun', 'domain:geography'],
  MOSCOW: ['proper_noun', 'domain:geography'],
  BERLIN: ['proper_noun', 'domain:geography'],
  MADRID: ['proper_noun', 'domain:geography'],
  ATHENS: ['proper_noun', 'domain:geography'],
  DUBLIN: ['proper_noun', 'domain:geography'],
  BOSTON: ['proper_noun', 'domain:geography'],
  CHICAGO: ['proper_noun', 'domain:geography'],
  DENVER: ['proper_noun', 'domain:geography'],
  SEATTLE: ['proper_noun', 'domain:geography'],
  MIAMI: ['proper_noun', 'domain:geography'],
  DALLAS: ['proper_noun', 'domain:geography'],
  HOUSTON: ['proper_noun', 'domain:geography'],
  ATLANTA: ['proper_noun', 'domain:geography'],
  PHOENIX: ['proper_noun', 'domain:geography'],
  DETROIT: ['proper_noun', 'domain:geography'],
  NASHVILLE: ['proper_noun', 'domain:geography'],
  PORTLAND: ['proper_noun', 'domain:geography'],
  ALASKA: ['proper_noun', 'domain:geography'],
  HAWAII: ['proper_noun', 'domain:geography'],
  TEXAS: ['proper_noun', 'domain:geography'],
  FLORIDA: ['proper_noun', 'domain:geography'],
  CALIFORNIA: ['proper_noun', 'domain:geography'],
  OREGON: ['proper_noun', 'domain:geography'],
  ARIZONA: ['proper_noun', 'domain:geography'],
  NEVADA: ['proper_noun', 'domain:geography'],
  UTAH: ['proper_noun', 'domain:geography'],
  IDAHO: ['proper_noun', 'domain:geography'],
  MAINE: ['proper_noun', 'domain:geography'],
  VERMONT: ['proper_noun', 'domain:geography'],
  KANSAS: ['proper_noun', 'domain:geography'],
  NEBRASKA: ['proper_noun', 'domain:geography'],
  IOWA: ['proper_noun', 'domain:geography'],
  OHIO: ['proper_noun', 'domain:geography'],
  INDIANA: ['proper_noun', 'domain:geography'],
  ILLINOIS: ['proper_noun', 'domain:geography'],
  MICHIGAN: ['proper_noun', 'domain:geography'],
  WISCONSIN: ['proper_noun', 'domain:geography'],
  MINNESOTA: ['proper_noun', 'domain:geography'],
  MISSOURI: ['proper_noun', 'domain:geography'],
  TENNESSEE: ['proper_noun', 'domain:geography'],
  KENTUCKY: ['proper_noun', 'domain:geography'],
  VIRGINIA: ['proper_noun', 'domain:geography'],
  MARYLAND: ['proper_noun', 'domain:geography'],
  DELAWARE: ['proper_noun', 'domain:geography'],
  PENNSYLVANIA: ['proper_noun', 'domain:geography'],
  CONNECTICUT: ['proper_noun', 'domain:geography'],
  MASSACHUSETTS: ['proper_noun', 'domain:geography'],
  RHODEISLAND: ['proper_noun', 'domain:geography'],
  NEWJERSEY: ['proper_noun', 'domain:geography'],
  NEWYORK: ['proper_noun', 'domain:geography'],
  NEWHAMPSHIRE: ['proper_noun', 'domain:geography'],
  MONTANA: ['proper_noun', 'domain:geography'],
  WYOMING: ['proper_noun', 'domain:geography'],
  COLORADO: ['proper_noun', 'domain:geography'],
  NEWMEXICO: ['proper_noun', 'domain:geography'],
  OKLAHOMA: ['proper_noun', 'domain:geography'],
  ARKANSAS: ['proper_noun', 'domain:geography'],
  LOUISIANA: ['proper_noun', 'domain:geography'],
  MISSISSIPPI: ['proper_noun', 'domain:geography'],
  ALABAMA: ['proper_noun', 'domain:geography'],
  GEORGIA: ['proper_noun', 'domain:geography'],
  CAROLINA: ['proper_noun', 'domain:geography'],
  VIRGINISLANDS: ['proper_noun', 'domain:geography'],
}

const abbreviations = new Set([
  'ABBR', 'ACCT', 'ADMIN', 'ADV', 'AFC', 'AFB', 'AFT', 'AGCY', 'ALTA', 'AMT',
  'APB', 'APO', 'APR', 'APT', 'ARC', 'ASSN', 'ASSOC', 'ATF', 'ATL', 'ATT',
  'AUG', 'AVE', 'AVG', 'BA', 'BAL', 'BD', 'BLDG', 'BLVD', 'BMW', 'BRA',
  'BRIT', 'BRO', 'BTU', 'CA', 'CAPT', 'CD', 'CEO', 'CFC', 'CFO', 'CIA',
  'CINC', 'CIO', 'CO', 'COL', 'COM', 'CON', 'CORP', 'COS', 'CPR', 'CST',
  'CT', 'CTR', 'DA', 'DC', 'DE', 'DEC', 'DEPT', 'DET', 'DIV', 'DJ',
  'DMV', 'DOA', 'DOC', 'DR', 'DST', 'DUI', 'DVD', 'E', 'EC', 'ED',
  'EEG', 'EEO', 'EFT', 'EG', 'EGO', 'EKG', 'EL', 'EM', 'ENL', 'ENT',
  'EPA', 'ER', 'ERA', 'EST', 'ET', 'ETAL', 'ETC', 'EU', 'EVA', 'EX',
  'EXAM', 'EXP', 'EXT', 'F', 'FAA', 'FBI', 'FCC', 'FDA', 'FDR', 'FED',
  'FEMA', 'FG', 'FI', 'FL', 'FLA', 'FM', 'FT', 'GA', 'GAS', 'GB',
  'GDP', 'GE', 'GI', 'GM', 'GMO', 'GMT', 'GNP', 'GOV', 'GOP', 'GPS',
  'GR', 'GSA', 'GST', 'GT', 'GTE', 'GTO', 'GUY', 'HA', 'HBO', 'HE',
  'HG', 'HI', 'HIV', 'HM', 'HMO', 'HQ', 'HR', 'HRS', 'HS', 'HUD',
  'IA', 'IBM', 'IC', 'ICE', 'ID', 'IDA', 'IE', 'IL', 'IM', 'IMF',
  'IN', 'INC', 'INF', 'INT', 'IOU', 'IP', 'IQ', 'IR', 'IRA', 'IRS',
  'IS', 'IT', 'IV', 'JA', 'JAG', 'JAN', 'JAP', 'JAR', 'JAX', 'JFK',
  'JR', 'JV', 'K', 'KA', 'KC', 'KG', 'KGB', 'KM', 'KO', 'KS',
  'KY', 'LA', 'LAB', 'LAD', 'LAN', 'LB', 'LBS', 'LC', 'LCD', 'LD',
  'LE', 'LED', 'LEG', 'LEV', 'LF', 'LG', 'LI', 'LIB', 'LIE', 'LII',
  'LIN', 'LIS', 'LL', 'LM', 'LN', 'LO', 'LP', 'LR', 'LS', 'LT',
  'LTD', 'LU', 'LV', 'M', 'MA', 'MAC', 'MAG', 'MAN', 'MAR', 'MAX',
  'MB', 'MC', 'MD', 'ME', 'MED', 'MEG', 'MEM', 'MES', 'MET', 'MEX',
  'MG', 'MI', 'MID', 'MIN', 'MISC', 'ML', 'MM', 'MN', 'MO', 'MOD',
  'MOM', 'MP', 'MR', 'MRS', 'MS', 'MSG', 'MT', 'MVP', 'N', 'NA',
  'NAB', 'NAD', 'NASA', 'NAT', 'NAV', 'NB', 'NC', 'ND', 'NE', 'NEA',
  'NEE', 'NEO', 'NET', 'NEV', 'NF', 'NG', 'NH', 'NI', 'NJ', 'NK',
  'NL', 'NM', 'NN', 'NO', 'NOR', 'NP', 'NR', 'NS', 'NSA', 'NT',
  'NV', 'NW', 'NY', 'NYC', 'O', 'OA', 'OAK', 'OB', 'OC', 'OD',
  'OE', 'OF', 'OG', 'OH', 'OI', 'OK', 'OL', 'OM', 'ON', 'ONE',
  'OO', 'OP', 'OR', 'ORG', 'OS', 'OT', 'OU', 'OV', 'OW', 'OX',
  'OZ', 'P', 'PA', 'PAC', 'PAL', 'PAN', 'PAR', 'PAT', 'PBS', 'PC',
  'PD', 'PE', 'PEN', 'PER', 'PET', 'PF', 'PG', 'PH', 'PI', 'PIN',
  'PK', 'PL', 'PM', 'PN', 'PO', 'POP', 'POT', 'PP', 'PR', 'PRE',
  'PRO', 'PS', 'PT', 'PU', 'PVC', 'PW', 'Q', 'QA', 'QC', 'QD',
  'QE', 'QI', 'QR', 'R', 'RA', 'RAD', 'RAM', 'RBI', 'RC', 'RD',
  'RE', 'REG', 'REP', 'RES', 'REV', 'RF', 'RG', 'RH', 'RI', 'RJ',
  'RK', 'RL', 'RM', 'RN', 'RO', 'RP', 'RR', 'RS', 'RT', 'RU',
  'RV', 'RW', 'RX', 'S', 'SA', 'SAC', 'SAM', 'SAN', 'SAT', 'SB',
  'SC', 'SD', 'SE', 'SEC', 'SEN', 'SEP', 'SF', 'SG', 'SH', 'SI',
  'SIG', 'SK', 'SL', 'SM', 'SN', 'SO', 'SP', 'SQ', 'SR', 'SS',
  'ST', 'STD', 'SU', 'SUB', 'SUN', 'SV', 'SW', 'SX', 'SY', 'T',
  'TA', 'TB', 'TC', 'TD', 'TE', 'TECH', 'TEL', 'TEMP', 'TEN', 'TF',
  'TG', 'TH', 'THU', 'TI', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO',
  'TP', 'TR', 'TS', 'TT', 'TU', 'TUE', 'TV', 'TW', 'TX', 'TY',
  'U', 'UA', 'UB', 'UC', 'UD', 'UE', 'UF', 'UG', 'UH', 'UI',
  'UK', 'UL', 'UM', 'UN', 'UP', 'UR', 'US', 'USA', 'UT', 'UV',
  'UX', 'V', 'VA', 'VAT', 'VB', 'VC', 'VD', 'VE', 'VF', 'VG',
  'VH', 'VI', 'VIP', 'VK', 'VL', 'VM', 'VN', 'VO', 'VP', 'VR',
  'VS', 'VT', 'VU', 'VV', 'VW', 'W', 'WA', 'WC', 'WD', 'WE',
  'WEB', 'WED', 'WF', 'WI', 'WK', 'WL', 'WM', 'WN', 'WO', 'WP',
  'WR', 'WS', 'WT', 'WU', 'WV', 'WW', 'WWW', 'WX', 'WY', 'X',
  'XL', 'XM', 'XP', 'XS', 'XT', 'XX', 'XXX', 'Y', 'YA', 'YB',
  'YC', 'YD', 'YE', 'YF', 'YG', 'YH', 'YI', 'YJ', 'YK', 'YL',
  'YM', 'YN', 'YO', 'YP', 'YQ', 'YR', 'YS', 'YT', 'YU', 'YV',
  'YW', 'YX', 'YY', 'YZ', 'Z', 'ZA', 'ZB', 'ZC', 'ZD', 'ZE',
  'ZF', 'ZG', 'ZH', 'ZI', 'ZJ', 'ZK', 'ZL', 'ZM', 'ZN', 'ZO',
  'ZP', 'ZQ', 'ZR', 'ZS', 'ZT', 'ZU', 'ZV', 'ZW', 'ZX', 'ZY', 'ZZ',
])

// Generate words from patterns + common roots
const consonants = 'BCDFGHJKLMNPQRSTVWXYZ'
const vowels = 'AEIOU'

function generateWords() {
  const words = new Set()

  // 3-letter words - all CVC combinations (subset)
  for (const c1 of consonants.slice(0, 10)) {
    for (const v of vowels) {
      for (const c2 of consonants.slice(0, 10)) {
        words.add(c1 + v + c2)
      }
    }
  }

  // Common prefixes/suffixes patterns
  const prefixes = ['RE', 'UN', 'PRE', 'DIS', 'MIS', 'OVER', 'UNDER', 'OUT', 'ANTI', 'PRO', 'SUB', 'SUPER', 'INTER', 'TRANS', 'NON', 'CO', 'DE', 'EN', 'EM', 'IN', 'IM', 'EX', 'EXTRA', 'INTRA', 'MULTI', 'SEMI', 'MID', 'MINI', 'MAXI', 'ULTRA', 'HYPER', 'AUTO', 'BI', 'TRI', 'QUAD', 'MONO', 'POLY', 'OMNI', 'SELF', 'ALL', 'UP', 'DOWN', 'OFF', 'ON']
  const roots = ['ACT', 'ART', 'BAT', 'BED', 'BIG', 'BOX', 'BOY', 'BUS', 'CAR', 'CAT', 'COW', 'CUT', 'DAY', 'DOG', 'EAR', 'EAT', 'EGG', 'EYE', 'FAR', 'FAT', 'FIT', 'FLY', 'FOX', 'FUN', 'GAP', 'GAS', 'GUN', 'HAT', 'HIT', 'HOT', 'HUG', 'ICE', 'JAM', 'JAR', 'JET', 'JOB', 'KEY', 'KID', 'LAP', 'LAW', 'LEG', 'LID', 'LIP', 'LOG', 'LOT', 'MAP', 'MAT', 'MIX', 'MOP', 'MUD', 'NET', 'NUT', 'OAK', 'OAR', 'OIL', 'OWL', 'PAD', 'PAN', 'PAT', 'PAY', 'PEN', 'PET', 'PIE', 'PIG', 'PIN', 'PIT', 'POT', 'RAG', 'RAM', 'RAT', 'RAW', 'RIB', 'RIM', 'ROB', 'ROD', 'ROT', 'RUB', 'RUG', 'SAD', 'SAP', 'SAW', 'SEA', 'SET', 'SEW', 'SIN', 'SIT', 'SKI', 'SKY', 'SOB', 'SOD', 'SON', 'SOW', 'SOY', 'SPA', 'SPY', 'STY', 'SUB', 'SUM', 'SUN', 'TAB', 'TAG', 'TAN', 'TAP', 'TAR', 'TAX', 'TEA', 'TEN', 'TIE', 'TIN', 'TIP', 'TOE', 'TON', 'TOP', 'TOW', 'TOY', 'TUB', 'TUG', 'URN', 'VAN', 'VAT', 'VET', 'VIA', 'VIE', 'VOW', 'WAR', 'WAX', 'WEB', 'WET', 'WIG', 'WIT', 'WOE', 'WOK', 'YAK', 'YAM', 'YAP', 'YAW', 'YEA', 'YEW', 'ZAP', 'ZEN', 'ZIP', 'ZOO']
  const suffixes = ['S', 'ED', 'ING', 'ER', 'EST', 'LY', 'NESS', 'MENT', 'TION', 'ABLE', 'IBLE', 'FUL', 'LESS', 'ISH', 'ISM', 'IST', 'ITY', 'IVE', 'OUS', 'EAL', 'AL', 'AR', 'OR', 'EE', 'EN', 'AN', 'IAN', 'EER', 'IER', 'EST', 'ATE', 'ITE', 'IZE', 'ISE', 'FY', 'IFY']

  for (const root of roots) {
    words.add(root)
    for (const pre of prefixes) {
      const w = pre + root
      if (w.length >= 3 && w.length <= 15) words.add(w)
    }
    for (const suf of suffixes) {
      const w = root + suf
      if (w.length >= 3 && w.length <= 15) words.add(w)
    }
  }

  // Add crosswordese set
  for (const w of crosswordese) words.add(w)

  // Add proper nouns
  for (const w of Object.keys(properNouns)) words.add(w)

  // Add abbreviations
  for (const w of abbreviations) words.add(w)

  // Extended common English words
  const common = `ABOUT ABOVE ABUSE ACTOR ACUTE ADAPT ADEPT ADMIT ADOPT ADORE ADULT AFTER AGAIN AGENT AGILE AGING ALARM ALBUM ALERT ALIEN ALIKE ALIVE ALLOW ALLOY ALOFT ALONE ALONG ALOUD ALPHA ALTER AMAZE AMBER AMEND AMONG AMPLE ANGEL ANGER ANGLE ANGRY ANKLE ANNEX ANNOY ANODE ANTIC ANVIL AORTA APART APPLE APPLY APRON ARENA ARGUE ARISE ARMOR AROMA AROSE ARROW ARTER ARTIC ASHES ASIDE ASKEW ASSET ATLAS ATTIC AUDIO AUDIT AVOID AWAKE AWARD AWARE AWFUL AXIOM AZURE BABES BACON BADGE BADLY BAGEL BAKER BALMY BANAL BANJO BARGE BARON BASAL BASIC BASIN BASIS BASTE BATCH BATHE BATON BATTY BAYOU BEACH BEADS BEADY BEARD BEAST BEAUT BEEFY BEECH BEING BELCH BELIE BELLE BELLY BELOW BENCH BERET BERRY BERTH BESET BETEL BEVEL BEZEL BIBLE BICEP BIDDY BIGOT BILGE BILLY BINGE BINGO BIOME BIRCH BIRTH BISON BITTY BLACK BLADE BLAME BLAND BLANK BLARE BLAST BLAZE BLEAK BLEAT BLEED BLEEP BLEND BLESS BLIMP BLIND BLINK BLISS BLITZ BLOAT BLOCK BLOKE BLOND BLOOD BLOOM BLOWN BLUER BLUFF BLUNT BLURB BLURT BLUSH BOARD BOAST BOBBY BODGE BOGEY BOGUS BOHEM BOLTS BONUS BOOBY BOOST BOOTH BOOTY BOOZE BOOZY BORAX BORNE BOSOM BOSSY BOTCH BOUGH BOULE BOUND BOWEL BOXER BRACE BRAID BRAIN BRAKE BRAND BRASH BRASS BRAVE BRAVO BRAWL BRAWN BREAD BREAK BREED BRIAR BRIBE BRICK BRIDE BRIEF BRINE BRING BRINK BRINY BRISK BROAD BROIL BROKE BROOD BROOK BROOM BROTH BROWN BRUNT BRUSH BRUTE BUDDY BUDGE BUGGY BUGLE BUILD BUILT BULGE BULKY BULLY BUNCH BUNNY BURST BUSed BUYER BYLAW CABIN CABLE CACAO CACHE CACTI CADDY CADET CAMEL CAMEO CANAL CANDY CANNY CANOE CANON CAPER CAPUT CARAT CARET CARGO CAROL CARVE CASTE CATCH CATER CATTY CAUSE CAVIL CEASE CEDAR CELLO CHAFE CHAFF CHAIN CHAIR CHALK CHAMP CHANT CHAOS CHARD CHARM CHART CHASE CHASM CHEAP CHEAT CHECK CHEEK CHEER CHESS CHEST CHICK CHIDE CHIEF CHILD CHILI CHILL CHIME CHINA CHIRP CHOCK CHOIR CHOKE CHORD CHORE CHOSE CHUCK CHUMP CHUNK CHURN CHUTE CIDER CIGAR CINCH CIRCA CIVIC CIVIL CLACK CLAIM CLAMP CLANG CLANK CLASH CLASP CLASS CLEAN CLEAR CLEAT CLEFF CLERK CLICK CLIFF CLIMB CLING CLINK CLOAK CLOCK CLONE CLOSE CLOTH CLOUD CLOUT CLOVE CLOWN CLUBS CLUCK CLUED CLUMP CLUNG COACH COAST COBRA COCOA COLON COLOR COMET COMFY COMIC COMMA CONCH CONDO CONIC COPSE CORAL CORER CORNY COUCH COUGH COVER COVET COVEY COWER COYLY CRACK CRAFT CRAMP CRANE CRANK CRASH CRASS CRATE CRAVe CRAWL CRAZY CREAK CREED CREEK CREEP CREME CREPE CREPT CRESS CREST CRICK CRIED CRIER CRIME CRIMP CRISP CROAK CROCK CRONE CROOK CROSS CROUP CROWD CROWN CRUDE CRUEL CRUSH CRUST CRYPT CUBIC CUMIN CURIO CURLY CURRY CURSE CURVE CURVY CUTIE CYBER CYCLE CYNIC DADDY DAILY DAIRY DAISY DALLY DANCE DANDY DATUM DAUNT DEALT DEATH DEBAR DEBIT DEBUG DEBUT DECAL DECAY DECOR DECOY DECRY DEFER DEIGN DEITY DELAY DELTA DELVE DEMON DEMON DENSE DEPOT DEPTH DERBY DETER DETOX DEUCE DEVIL DIARY DICEY DIGIT DILLY DIMLY DINER DINGO DINGY DIODE DIRGE DIRTY DISCO DITTO DITTY DIVER DIZZY DODGE DODGY DOLLY DONOR DONUT DOPEY DOUBT DOUGH DOWDY DOWEL DOWNY DOWRY DOZEY DOZEN DRAFT DRAIN DRAKE DRAM DRAMA DRANK DRAPE DRAW DRANK DRAFT DRAIN DRAKE DRAMA DRANK DRAPE DRAFT DRAIN DRAPE DREAD DREAM DRESS DRIED DRIER DRIFT DRILL DRINK DRIVE DROIT DROLL DRONE DROOL DROOP DROVE DROWN DRUID DRUNK DRYER DRYLY DUCHY DULLY DUMMY DUMPY DUNCE DUSKY DUSTY DUTCH DUVET DWARF DWELL DWELT DYING EAGER EAGLE EARLY EARTH EASEL EATEN EATER EBONY ECLAT EDIFY EERIE EGRET EIGHT EJECT ELANE ELBOW ELDER ELECT ELEGy ELITE ELOPE ELSIE ELUDE EMAIL EMBED EMBER EMCEE EMPTY ENACT ENDOW ENEMY ENJOY ENNUI ENSUE ENTER ENTRY ENVOY EPIC EPOCH EPOXY EQUAL EQUIP ERASE ERECT ERODE ERROR ERUPT ESSAY ESTER ETUDE EVADE EVENT EVERY EVICT EVOKE EXACT EXALT EXCEL EXERT EXILE EXIST EXPEL EXTOL EXTRA EXULT EYING FABLE FACET FAINT FAIRY FAITH FALSE FANCY FARCE FATAL FATTY FAULT FAUNA FAVOR FEAST FECAL FEIGN FELLA FELON FEMUR FENCE FERAL FERRY FETAL FETCH FETID FETUS FEUD FEVER FEWER FIBER FIBRE FICUS FIELD FIEND FIERY FIFTH FIFTY FIGHT FILCH FILET FILLY FILMY FILTH FINAL FINCH FINER FINNY FIRTH FIRST FISHY FIXER FIZZY FLACK FLAIL FLAIR FLAKE FLAKY FLAME FLANK FLARE FLASH FLASK FLAT FLAW FLAX FLAY FLEA FLECK FLEET FLESH FLICK FLIER FLING FLINT FLIRT FLOAT FLOCK FLOOD FLOOR FLOP FLOSS FLOUR FLOUT FLOW FLOWN FLUFF FLUID FLUKE FLUME FLUNG FLUNK FLUSH FLUTE FLYER FOAMY FOCAL FOCUS FOGGY FOIST FOLIO FOLLY FORAY FORCE FORGE FORGO FORTE FORTH FORTY FORUM FOUND FOWLS FOXES FOXY FOYER FRAIL FRAME FRANK FRAUD FRESH FREON FRIAR FRIB FRICK FRIDO FRIED FRILL FRISK FRITZ FRIZZ FRIZ FROCK FROGS FROND FRONT FROST FROTH FROWN FROZE FRUIT FRYER FUDGE FUGUE FULLY FUNGI FUNKY FUNNY FUROR FURRY FUSSY FUZZY GAFFE GAILY GAMER GAMMA GAMUT GASSY GAUDY GAUGE GAUNT GAUZE GAVEL GAWKY GAYER GAYLY GAZER GECKO GEESE GENIE GENRE GHOST GIANT GIDDY GIFT GIGGL GIRLY GIRTH GIVEN GIVER GLADE GLAND GLARE GLASS GLAZE GLEAM GLEAN GLIDE GLINT GLOAT GLOBE GLOOM GLORY GLOSS GLOVE GLYPH GNASH GNOME GOADS GOAL GOATS GOBBLE GODLY GOING GOLLY GONER GOODY GOOEY GOOFY GOOSE GORGE GOUGE GOURD GRACE GRADE GRAIL GRAIN GRAND GRANT GRAPE GRAPH GRASP GRASS GRATE GRAVY GRAZE GREAT GREED GREEN GREET GRIEF GRILL GRIME GRIMY GRIND GRIPE GROAN GROIN GROOM GROPE GROSS GROUP GROUT GROVE GROW GROWL GROWN GRUEL GRUFF GRUNT GUARD GUESS GUEST GUIDE GUILD GUILE GUILT GUISE GULCH GULLY GUMBO GUMMY GUPPY GUSTO GUSTY GUTSY GYPSY HABIT HAIRY HALVE HANDY HAPPY HARDY HARSH HASTE HASTY HATCH HATER HAUNT HAVEN HAVOC HAZEL HEADY HEARD HEART HEATH HEAVE HEAVY HEDGE HEEDY HEFTY HEIST HELIX HELLO HENCE HERBS HERDS HERON HERO HERTZ HEWER HIDE HILLY HILT HIND HINGE HIPPO HIPPY HITCH HIVES HOARD HOBBY HOIST HOLLY HOMER HONEY HONOR HOOCH HOOD HOOK HOOP HOOT HORDE HORNY HORSE HOTEL HOTLY HOUND HOUSE HOVEL HOVER HOWDY HOWL HUMAN HUMID HUMOR HUMPH HUNCH HUNKY HURRY HUSKY HUSSY HUTCH HYDRA HYENA HYMEN HYPER ICING IDEAL IDIOM IDIOT IDLE IDYLL IGLOO ILIAC IMAGE IMAM IMPEL INANE INBOX INCUR INDEX INDIE INERT INFER INGOT INLAY INLET INNER INPUT INTER INTRO IONIC IRATE IRONY ISLET ISSUE ITCHY IVORY JADED JAIL JANET JAPAN JAZZY JEANS JELLY JERKY JETTY JEWEL JIFFY JOINT JOKER JOLLY JOUST JUDGE JUICE JUICY JUMBO JUMPY JUNTA JUNTO JUROR KAPPA KARMA KAYAK KAZOO KEBAB KHAKI KIOSK KNACK KNAVE KNEAD KNEED KNEEL KNELT KNIFE KNOCK KNOLL KNOT KNOWN KOALA KRILL LABEL LABOR LADEN LADLE LAGER LANCE LAND LANKY LAPEL LAPSE LARGE LARVA LASER LASSO LATCH LATER LATHE LATTE LAUGH LAYER LEACH LEADS LEAF LEAK LEAN LEAP LEARN LEASE LEASH LEAST LEAVE LEDGE LEECH LEERY LEFT LEGAL LEGGY LEMON LEMUR LENNY LEper LEVEL LEVER LIBEL LIBRA LICIT LIEGE LIGHT LIKEN LILAC LIMBO LIMIT LINEN LINER LINGO LIPID LITHE LIVER LIVID LLAMA LOAMY LOATH LOBBY LOCAL LOCUS LODGE LOFTY LOGIC LOGIN LOOPY LOOSE LORRY LOSER LOUSE LOUSY LOVER LOWER LOWLY LOYAL LUCID LUCKY LUMEN LUMPY LUNAR LUNCH LUNGE LUPUS LURCH LURE LURID LUSTY LYING LYMPH LYNCH LYRIC MACAW MACHO MACRO MADAM MADLY MAGIC MAGMA MAIZE MAJOR MAKER MAMBO MAMMY MANGA MANGE MANGO MANGY MANIA MANIC MANLY MANOR MAPLE MARCH MARRY MARSH MASON MASSE MATCH MATE MATEY MAUVE MAXIM MAYBE MAYOR MEALY MEANT MEAT MEATY MECCA MEDAL MEDIA MEDIC MELON MERCY MERGE MERIT MERRY METAL METER METRO MICRO MIDGE MIDST MIGHT MILKY MIMIC MINCE MINER MINIM MINOR MINT MINTY MINUS MIRTH MISER MISSY MOCHA MODAL MODEL MODEM MOGUL MOIST MOLAR MOLDY MONEY MONTH MOODY MOOSE MORAL MORON MORPH MOSSY MOTEL MOTIF MOTOR MOTTO MOULT MOUND MOUNT MOURN MOUSE MOUTH MOVER MOVIE MOWER MOXIE MUDDY MULCH MUMMY MUNCH MURAL MURKY MUSHY MUSIC MUSKY MUSTY MYRRH NACHO NADIR NAIVE NANNY NASAL NASTY NATAL NAVAL NAVEL NEAR NEAT NECTAR NEEDY NEIGH NERDY NERVE NERVY NEVER NEWER NEWLY NICER NICHE NIECE NIGHT NINJA NINNY NINTH NOBLE NOBLY NOISE NOISY NOMAD NOOSE NORTH NOSE NOTCH NOVEL NUDGE NURSE NUTTY NYLON NYMPH OAKEN OBESE OCCUR OCEAN OCTAL OCTET ODDS ODOR OFFAL OFFER OFTEN OLDER OLIVE OMEGA ONION ONSET OPERA OPIUM OPTIC ORBIT ORDER ORGAN OTHER OTTER OUGHT OUNCE OUTDO OUTER OUTGO OVARY OVATE OVERT OVOID OWING OWLET OWNER OXIDE OZONE PADDY PAGAN PAINT PALER PALSY PANEL PANIC PANSY PAPAL PAPER PARER PARKA PARRY PARSE PARTY PASTA PASTE PASTY PATCH PATIO PATSY PATTY PAUSE PAYEE PAYER PEACE PEACH PEARL PEDAL PENAL PENCE PENNE PENNY PERCH PERIL PERKY PESKY PETAL PETTY PHASE PHONE PHONY PHOTO PIANO PICK PICKY PIECE PIETY PILOT PINCH PINE PINKY PINT PINTO PIPER PITHY PIXEL PIXIE PIZZA PLACE PLAID PLAIN PLAIT PLANE PLANK PLANT PLATE PLAZA PLEAD PLEAT PLIED PLIER PLUCK PLUG PLUMB PLUME PLUMP PLUNK PLUSH POESY POINT POISE POKER POLAR POLKA POLYP PONCE POOCH POPPY PORCH POSED POSER POSSE POUCH POUND POUS POVEY POWER PRANK PRAWN PRESS PRICE PRICK PRIDE PRIED PRIME PRIMO PRIMP PRINT PRIOR PRISM PRIVY PRIZE PROBE PRONE PRONG PROOF PROSE PROUD PROVE PROVO PROWL PROXY PRUDE PRUNE PSALM PUBIC PUDGY PUFFY PULPY PULSE PUMPS PUNCH PUPAL PUPIL PUPPY PURE PURGE PURSE PUSHY PUTTY PYGMY QUACK QUAIL QUAK QUARK QUART QUASH QUASI QUEEN QUEER QUELL QUERY QUEST QUEUE QUICK QUIET QUILT QUIRK QUITE QUOTA QUOTE RABBI RABID RACER RADAR RADII RADIO RAIN RAFT RALLY RALPH RAMEN RANCH RANDY RANGE RAPID RASPY RATIO RATTY RAVEN RAYON RAZOR REACH REACT READY REALM REBEL REBUS REBUT RECAP RECUR REDO REFER REFIT REGAL REHAB REIGN RELAX RELAY RELIC REMIT RENAL RENEW REPAY REPEL REPLY RERUN RESIN RETCH RETRO REUSE REVEL REVUE RHINO RHYME RIDER RIDGE RIFLE RIGHT RIGID RIGOR RINSE RIPEN RISER RISK RITZY RIVAL RIVER RIVET ROACH ROAST ROBIN ROBOT ROCK ROCKY RODE ROGUE ROOM ROOST ROTOR ROUGE ROUGH ROUND ROUSE ROUTE ROVER ROWDY ROYAL RUDDY RUGBY RULER RUMBA RUMOR RUPEE RURAL RUST RUSTY SADLY SAFER SAINT SALAD SALLY SALON SALSA SALTY SALVE SALVO SAND SANER SAPPY SASSY SATIN SATYR SAUCE SAUCY SAUNA SAUTE SAVOR SAVVY SCALD SCALE SCALL SCALP SCANT SCARE SCARF SCARY SCENE SCENT SCOFF SCOLD SCOOP SCORE SCORN SCOUR SCOUT SCOWL SCRAM SCRAP SCRE SCRUB SCRUM SCUBA SEDAN SEEDY SEGUE SEIZE SEMEN SENSE SEPIA SERIF SERUM SERVE SETUP SEVEN SEVER SEWER SHACK SHADE SHAFT SHAKE SHAKY SHALL SHALT SHAME SHANK SHAPE SHARD SHARE SHARK SHARP SHAVE SHAWL SHEAR SHEEN SHEEP SHEER SHEET SHEIK SHELF SHELL SHIED SHIFT SHINE SHINY SHIRE SHIRK SHIRT SHOAL SHOCK SHONE SHOOK SHOOT SHORE SHORN SHORT SHOUT SHOVE SHOWN SHOWY SHREW SHRUB SHRUG SHUCK SHUNT SHUSH SHYLY SIEGE SIEVE SIGHT SIGMA SILKY SILLY SINCE SINEW SING SINGE SIRE SIREN SISAL SIXTH SIXTY SKATE SKIER SKIFF SKILL SKIMP SKIRT SKULK SKULL SKUNK SLACK SLAIN SLANG SLANT SLASH SLATE SLAVE SLEEK SLEEP SLEET SLICE SLICK SLIDE SLIME SLIM SLIMY SLING SLINK SLOOP SLOPE SLOSH SLOTH SLUMP SLUNG SLUNK SLUR SLURP SLUSH SLYLY SMACK SMALL SMART SMASH SMEAR SMELL SMELT SMILE SMIRK SMITE SMITH SMOCK SMOG SMOKE SMOKY SMOTE SNACK SNAFU SNAIL SNAKE SNAKY SNARE SNARL SNEAK SNEER SNIDE SNIFF SNipe SNORE SNORT SNOUT SNOW SNOWY SNUCK SNUFF SOAP SOBER SOGGY SOLAR SOLID SOLVE SONAR SONIC SOOTH SOOTY SORRY SOUND SOUTH SOWER SPACE SPADE SPANK SPARE SPARK SPASM SPATE SPAWN SPEAK SPEAR SPECK SPEED SPELL SPELT SPEND SPENT SPEW SPICE SPICY SPIED SPIEL SPIKE SPIKY SPILL SPILT SPINE SPINY SPIRE SPITE SPLAT SPLIT SPOIL SPOKE SPOOF SPOOK SPOOL SPOON SPORE SPORT SPOUT SPRAY SPREE SPRIG SPUD SPUNK SPURN SPURT SQUAD SQUAT SQUIB STACK STAFF STAGE STAID STAIN STAIR STAKE STALE STALK STALL STAMP STAND STANK STARE STARK START STASH STATE STAVE STAY STEAD STEAK STEAL STEAM STEED STEEL STEEP STEER STEM STEP STER STICK STIFF STILL STILT STING STINK STINT STOCK STOIC STOKE STOLE STOMP STONE STONY STOOD STOOL STOOP STORE STORK STORM STORY STOUT STOVE STRAP STRAW STRAY STRIP STRIT STRUM STRUT STUCK STUD STUDY STUFF STUMP STUNG STUNK STUNT STYLE SUAVE SUEDE SUGAR SUING SUITE SULKY SULLY SUMAC SUNNY SUPER Surer SURGE SURLY SUSHI SWAMI SWAMP SWARM SWASH SWATH SWAY SWEAR SWEAT SWEEP SWEET SWELL SWEPT SWIFT SWILL SWINE SWING SWIRL SWISH SWOON SWOOP SWORD SWORE SWORN SWUNG SYRUP TABBY TABLE TABOO TACIT TACKY TAFFY TAINT TAKEN TAKER TALLY TALON TAMER TANGO TANGY TAPER TAPIR TARDY TAROT TASTE TASTY TATTY TAUNT TAWNY TEACH TEAK TEAM TEAR TEASE TEEN TEMPO TENOR TENSE TENT TEPID TERSE TEST TESTY THANK THEFT THEIR THEME THERE THESE THICK THIEF THIGH THING THINK THIRD THONG THORN THOSE THREE THREW THROB THROW THRUM THUMB THUMP THYME TIARA TIBIA TIDAL TIGER TIGHT TILDE TIMER TIMID TIPSY TITAN TITHE TITLE TOAST TODAY TODDY TOKEN TONAL TONGS TONIC TOOTH TOPAZ TOPIC TORCH TORSO TORUS TOTAL TOTEM TOUCH TOUGH TOWEL TOWER TOXIC TOXIN TRACE TRACK TRACT TRADE TRAIL TRAIN TRAIT TRAMP TRASH TRAWL TREAT TREND TRIAD TRIAL TRIBE TRICE TRICK TRIED TRIPE TRITE TROLL TROOP TROPE TROTH TROUT TROVE TRUce TRUCK TRUER TRULY TRUMP TRUNK TRUSS TRUST TRUTH TRYST TUBAL TUBER TULIP TULLE TUMOR TUNIC TURBO TUTOR TWANG TWEAK TWEED TWEET TWICE TWINE TWIRL TWIST TWIXT TYING UDDER UGLY ULTRA UMBER UMBRA UNARM UNARY UNCUT UNDER UNDID UNDUE UNFED UNFIT UNIFY UNION UNITE UNITY UNLIT UNMET UNSET UNTIE UNTIL UNWED UNZIP UPPER UPSET URBAN URINE USAGE USHER USING USUAL USURP UTILE UTTER UVULA VAGUE VALET VALID VALOR VALUE VALVE VAPID VAPOR VAULT VAUNT VEGAN VENOM VENUE VERGE VERSE VERSO VERVE VICAR VIDEO VIGIL VIGOR VILLA VINYL VIOLA VIPER VIRAL VIRUS VISIT VISOR VISTA VITAL VIVID VIXEN VOCAL VODKA VOGUE VOICE VOILA VOMIT VOTER VOUCH VOWEL VYING WAFER WAGER WAGON WAIST WAIVE WALTZ WART WASTE WATCH WATER WAVER WAVY WAXEN WEARY WEAVE WEDGE WEED WEEDY WEEP WEIGH WEIRD WELCH WELSH WHACK WHALE WHARF WHEAT WHEEL WHELP WHERE WHERR WHICH WHIFF WHILE WHINE WHINY WHIRL WHISK WHITE WHOLE WHOOP WHOSE WIDEN WIDOW WIDTH WIELD WIGHT WILLY WIMPY WINCE WINCH WIND WINDY WINER WINK WIPER WIRER WIRY WISER WISPY WITCH WITTY WOKEN WOMAN WOMEN WOOER WOOL WOODS WOODY WOOER WOOZY WORD WORK WORLD WORM WORRY WORSE WORST WORTH WOULD WOUND WRACK WRATH WREAK WRECK WREST WRING WRIST WRITE WRONG WROTE WRUNG WRYLY YACHT YEARN YEAST YIELD YOUNG YOUTH YUKON ZEBRA ZESTY ZONAL`.split(/\s+/)

  for (const w of common) {
    if (w.length >= 3 && w.length <= 15 && /^[A-Z]+$/.test(w)) words.add(w)
  }

  return [...words].filter((w) => w.length >= 3 && w.length <= 15)
}

function scoreWord(word) {
  const w = word.toUpperCase()
  if (properNouns[w]) return { score: 55, tags: properNouns[w] }
  if (abbreviations.has(w)) return { score: 35, tags: ['abbreviation'] }
  if (crosswordese.has(w)) return { score: 25, tags: ['crosswordese'] }
  return scoreWordByLength(w)
}

const words = generateWords()
const entries = words.map((word) => {
  const { score, tags } = scoreWord(word)
  return { word, score, tags, excluded: false }
})

// Dedupe
const seen = new Set()
const unique = entries.filter((e) => {
  if (seen.has(e.word)) return false
  seen.add(e.word)
  return true
})

unique.sort((a, b) => a.word.localeCompare(b.word))
console.log(`Generated ${unique.length} words`)
writeFileSync(join(outDir, 'words.json'), JSON.stringify(unique))
