import type { LicensePlateRegion } from '../types';

/** US states + DC and Canadian provinces/territories (plategame.app set). */
export const LICENSE_PLATE_REGIONS: LicensePlateRegion[] = [
  { id: 'alabama', label: 'Alabama', group: 'us' },
  { id: 'alaska', label: 'Alaska', group: 'us' },
  { id: 'arizona', label: 'Arizona', group: 'us' },
  { id: 'arkansas', label: 'Arkansas', group: 'us' },
  { id: 'california', label: 'California', group: 'us' },
  { id: 'colorado', label: 'Colorado', group: 'us' },
  { id: 'connecticut', label: 'Connecticut', group: 'us' },
  { id: 'delaware', label: 'Delaware', group: 'us' },
  { id: 'district_of_columbia', label: 'District Of Columbia', group: 'us' },
  { id: 'florida', label: 'Florida', group: 'us' },
  { id: 'georgia', label: 'Georgia', group: 'us' },
  { id: 'hawaii', label: 'Hawaii', group: 'us' },
  { id: 'idaho', label: 'Idaho', group: 'us' },
  { id: 'illinois', label: 'Illinois', group: 'us' },
  { id: 'indiana', label: 'Indiana', group: 'us' },
  { id: 'iowa', label: 'Iowa', group: 'us' },
  { id: 'kansas', label: 'Kansas', group: 'us' },
  { id: 'kentucky', label: 'Kentucky', group: 'us' },
  { id: 'louisiana', label: 'Louisiana', group: 'us' },
  { id: 'maine', label: 'Maine', group: 'us' },
  { id: 'maryland', label: 'Maryland', group: 'us' },
  { id: 'massachusetts', label: 'Massachusetts', group: 'us' },
  { id: 'michigan', label: 'Michigan', group: 'us' },
  { id: 'minnesota', label: 'Minnesota', group: 'us' },
  { id: 'mississippi', label: 'Mississippi', group: 'us' },
  { id: 'missouri', label: 'Missouri', group: 'us' },
  { id: 'montana', label: 'Montana', group: 'us' },
  { id: 'nebraska', label: 'Nebraska', group: 'us' },
  { id: 'nevada', label: 'Nevada', group: 'us' },
  { id: 'new_hampshire', label: 'New Hampshire', group: 'us' },
  { id: 'new_jersey', label: 'New Jersey', group: 'us' },
  { id: 'new_mexico', label: 'New Mexico', group: 'us' },
  { id: 'new_york', label: 'New York', group: 'us' },
  { id: 'north_carolina', label: 'North Carolina', group: 'us' },
  { id: 'north_dakota', label: 'North Dakota', group: 'us' },
  { id: 'ohio', label: 'Ohio', group: 'us' },
  { id: 'oklahoma', label: 'Oklahoma', group: 'us' },
  { id: 'oregon', label: 'Oregon', group: 'us' },
  { id: 'pennsylvania', label: 'Pennsylvania', group: 'us' },
  { id: 'rhode_island', label: 'Rhode Island', group: 'us' },
  { id: 'south_carolina', label: 'South Carolina', group: 'us' },
  { id: 'south_dakota', label: 'South Dakota', group: 'us' },
  { id: 'tennessee', label: 'Tennessee', group: 'us' },
  { id: 'texas', label: 'Texas', group: 'us' },
  { id: 'utah', label: 'Utah', group: 'us' },
  { id: 'vermont', label: 'Vermont', group: 'us' },
  { id: 'virginia', label: 'Virginia', group: 'us' },
  { id: 'washington', label: 'Washington', group: 'us' },
  { id: 'west_virginia', label: 'West Virginia', group: 'us' },
  { id: 'wisconsin', label: 'Wisconsin', group: 'us' },
  { id: 'wyoming', label: 'Wyoming', group: 'us' },
  { id: 'alberta', label: 'Alberta', group: 'canada' },
  { id: 'british_columbia', label: 'British Columbia', group: 'canada' },
  { id: 'manitoba', label: 'Manitoba', group: 'canada' },
  { id: 'new_brunswick', label: 'New Brunswick', group: 'canada' },
  { id: 'newfoundland_and_labrador', label: 'Newfoundland and Labrador', group: 'canada' },
  { id: 'northwest_territories', label: 'Northwest Territories', group: 'canada' },
  { id: 'nova_scotia', label: 'Nova Scotia', group: 'canada' },
  { id: 'nunavut', label: 'Nunavut', group: 'canada' },
  { id: 'ontario', label: 'Ontario', group: 'canada' },
  { id: 'prince_edward_island', label: 'Prince Edward Island', group: 'canada' },
  { id: 'quebec', label: 'Quebec', group: 'canada' },
  { id: 'saskatchewan', label: 'Saskatchewan', group: 'canada' },
  { id: 'yukon_territory', label: 'Yukon Territory', group: 'canada' },
];
